infrastructure/.prettierrc
infrastructure/src/hasura/parameters/index.ts
infrastructure/src/web/index.ts
infrastructure/src/web/parameters/dev.ts
infrastructure/src/web/parameters/index.ts
infrastructure/src/web/parameters/production.ts
infrastructure/src/web/parameters/staging.ts

- Apply scaling config from env to web stack.
- [memoryLimitMiB](https://github.com/worldcoin/developer-portal/pull/22/files#diff-5c7ebedf2c6e3d6d3f905943277c1005bdb48a827b30fd46c089adf585834fbeR76)
- [cpu](https://github.com/worldcoin/developer-portal/pull/22/files#diff-5c7ebedf2c6e3d6d3f905943277c1005bdb48a827b30fd46c089adf585834fbeR78)
- [configureHealthCheck](https://github.com/worldcoin/developer-portal/pull/22/files#diff-5c7ebedf2c6e3d6d3f905943277c1005bdb48a827b30fd46c089adf585834fbeR136-R142)
- [autoScaleTaskCount](https://github.com/worldcoin/developer-portal/pull/22/files#diff-5c7ebedf2c6e3d6d3f905943277c1005bdb48a827b30fd46c089adf585834fbeR146-R151)
- [scaleOnCpuUtilization](https://github.com/worldcoin/developer-portal/pull/22/files#diff-5c7ebedf2c6e3d6d3f905943277c1005bdb48a82 …

chore: hide scaling params at web stack

---

web/api-helpers/jwts.ts
web/api-helpers/oidc.ts
web/consts.ts
web/next.config.js
web/pages/api/v1/jwks.ts
web/pages/api/v1/oidc/authorize.ts
web/pages/api/v1/oidc/openid-configuration.ts
web/pages/api/v1/oidc/token.ts
web/pages/api/v1/oidc/userinfo.ts

We now use a single domain for OIDC, `https://id.worldcoin.org`, endpoints are now very friendly in that domain.

feat: OIDC single domain

---

web/src/scenes/actions/Action/ActionHeader.tsx

Pressing the space bar inside the input field would collapse or expand the action block. Now the event propogation stops.

fix: prevent disclosure opening when space bar is pressed in input

---

web/src/scenes/app/Configuration.tsx

Added message that appears when hovering over the field, if the application is verified.

feat: add hint for app name field

---

hasura/metadata/cron_triggers.yaml
hasura/metadata/databases/default/tables/public_api_key.yaml
web/src/backend/jwks.ts
web/src/backend/kms.ts
web/src/pages/api/_delete-jwks.ts
web/src/pages/api/_gen-jwks.ts
web/tests/api/__mocks__/kms.mock.ts
web/tests/api/delete-jwks.test.ts
web/tests/api/gen-jwks.test.ts

Adds a cron trigger to Hasura to call the `/_delete-jwks` endpoint every hour, which will schedule all expired jwks for deletion within KMS.  Additionally, the expiration date is now directly pulled from the KMS key creation event.

feat: call _delete-jwks using a cron trigger

---

web/src/components/FieldLabel/index.tsx
web/src/scenes/actions/NewAction/index.tsx
web/src/scenes/actions/UpdateAction/index.tsx

Related to [Slack message](https://ottofeller.slack.com/archives/C04R16D5EAH/p1681039075858379?thread_ts=1680868006.965309&cid=C04R16D5EAH)
Closes [WID-428](https://linear.app/worldcoin/issue/WID-428/updateadd-new-action-modals-missing-description-caption)
- Adds descriptions under the field label
- Makes description required. (with `(public)` label)
---
https://user-images.githubusercontent.com/89008845/232761870-51bb5a0b-dc83-4c26-a332-885fe9e6b427.mp4

refactor: update new app & update app modals

---

web/src/pages/api/login.ts

Rather than adding and removing functionality in the codebase for each conference, we can simplify to a single environment variable: CONFERENCE_INVITE_CODE.
If the environment variable is set, then it can be used as an invite code for hackathon participants. When the conference is finished, we can simply delete the environment variable; the code gracefully handles the condition where the environment variable is undefined.

feat: add conference invite code functionality

---

.snyk
web/Dockerfile
web/pnpm-lock.yaml
web/src/api/auth/login-callback.ts

after updating nextjs version, I can't reproduce socket error with 2+ queries, so removing temp`wait` function on login-callback

chore: revert temp fix

---

hasura/migrations/default/1699244895189_alter_table_public_user_alter_column_world_id_nullifier/down.sql
hasura/migrations/default/1699244895189_alter_table_public_user_alter_column_world_id_nullifier/up.sql

With the introduction of Auth0, users will now be able to log in with other methods, without using World ID. This PR allows creating users without a nullifier hash.

fix: world_id_nullifier no longer required

---

web/src/pages/api/v1/verify/[app_id].ts

Uses an empty string as the signal if one is not provided on the `/verify` endpoint.
Since the signal is not a required parameter for IDKit, it doesn't make sense for it to also be required on the API verification endpoint. As long as both default to the same value (an empty string) then this should be fine.

feat: default empty string for signal on `/verify` endpoint

---

web/src/pages/api/v1/oidc/authorize.ts
web/src/pages/api/v1/precheck/[app_id].ts
web/tests/api/precheck.test.ts

1. Allows optional attributes in `/precheck` to be `null` in addition to empty strings for better support of other clients.
2. Enforces `nonce` / signal when using Sign in with Worldcoin. CC @0xPenryn

fix: attributes in /precheck can be null & enforce nonce in Sign in with Worldcoin

---

web/src/api/signup/graphql/signup.generated.ts
web/src/api/signup/graphql/signup.graphql
web/src/api/signup/index.ts

Empty string `""` was used as fallback in Signup query for `email` or `nullified_hash` in case we don't have some of this data.
But `email` and `world_id_nullifier` fields have a uniqueness rule, so in case we have someone in database with `""` email or nullifier_hash it will throw an error. 
I've updated code to pass these fields only if we have data. In this case, the missing field will be written as `null`

fix: signup query

---

web/src/pages/api/v1/precheck/[app_id].ts

Problem: 
- When passing null to `nullifier_hash` with `nullable` the default value not applies.
- After this we passing null to the gql query where we expect String type and this is throws an error. 
Fix: 
- Add additional `transform` to the schema to convert `null` to `""`

fix: precheck

---

web/src/components/Layout/LoggedUserDisplay/TeamSelector/index.tsx

fix: text overflow on team selector

---

web/src/scenes/sign-in-with-world-id/Credentials/index.tsx
web/src/scenes/sign-in-with-world-id/index.tsx

Closes [this](https://tfh.slack.com/archives/C05NJ4QFCLE/p1706041937278389?thread_ts=1706031364.968379&cid=C05NJ4QFCLE) and [this](https://tfh.slack.com/archives/C05NJ4QFCLE/p1706042415683769?thread_ts=1706031364.968379&cid=C05NJ4QFCLE)
We using Hasura action `_reset-secret-key` to reset secret key and there is only two options for actions: allow or forbid action for the entire user role, so I decided simply not show client secret section for the members
Also hide Redirects and Urls components from MEMBER on /sign-in page

fix: hide secret section for members

---

web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/layout/index.tsx
web-app-router/styles/globals.css

I update toasts css to be bottom right and thinner with no progress bar like in the specs. I don't think it's worth to change the icons since I think the default ones actually look better and it seems we need to manually inject the icon for each toast. 
Merging this directly into WID 679

Fix: Update Toast Format WID-692

---

web-app-router/next-env.d.ts
web/src/hooks/useApps.ts

There's a bug with the filter function which is supposed ensure we remove any null values added to the array from react-hook-form. If the app is in an empty state you cannot save without a showcase image since the url is null and url.startsWith() will throw an error.
The fix is using a loose check for null, should catch null and undefined

fix: On save fix

---

hasura/metadata/databases/default/tables/public_action_stats_returning.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1707463125126_create_action_stats_table/down.sql
hasura/migrations/default/1707463125126_create_action_stats_table/up.sql
web-app-router/graphql/graphql.schema.json

Added hasura table for action_stats_returning
I need to test the actual table with the chart still, but the migrations run fine with no troubles
We need to rebase still to pull in the verify_app query and other changes that got merged to main

WID 745: Hasura Changes for Create Action Stats

---

hasura/migrations/default/1707493190197_alter_table_public_user_alter_column_team_id/down.sql
hasura/migrations/default/1707493190197_alter_table_public_user_alter_column_team_id/up.sql

When we delete a team, the relationship is also removed from the membership table, along with any associated applications and actions. This is achieved through foreign constraints.
However, currently, the user is also deleted along with the team. To prevent this from happening, I've adjusted the team_id field, making it nullable, and also updated the constraint.
We're not using the team_id field in the user table; it's kept for backward compatibility with the old frontend. We'll need to remove it entirely.

feat: update user constraint

---

web/components/Link/index.tsx

With prefetch, next's Link adds some query params to the URL. And, for example, the logout URL will be something like `/api/auth/logout?param=value`. This caused errors on the auth0 side because we need to configure callback, logout, login, etc strictly. Prefetch caused a URL mismatch.

fix: link prefetch

---

web/components/DialogPanel/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/MiniKiosk/IDKitBridge/index.tsx

Before it was changing screen state in idkit as well which is causing weird flashes. We rely on proof verification endpoint to determine if it should be in error or success state.

[Fix] Make mini kiosk more stable

---

web/scenes/Portal/layout/CreateAppDialog/index.tsx

Small responsiveness fix. Just want to make sure when we push that users can activate through verifying an action before responsiveness comes

[Fix] Responsiveness temp fix

---

web/components/InitialSteps/index.tsx
web/lib/genarate-title.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/ImageDisplay/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/ImageLoader/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/index.tsx

- ImageLoader
- Added a hotfix to logo image upload. Essentially since we fix the image url path for logo_img.png/jpg. The image is caching on the browser. However, we cannot append any params to the signed_url since it will invalidate the URL. Thus we need to modify the way we upload images to generate a random string each time to invalidate the cache. We handle this for now by refreshing the page if it's their second upload. I will revisit this after merge because it will require large backend changes. Note this also will affect showcase and banner image. But logo is more prominent, on every page, so I hotfix that for now. 
- I also changed the meta tag to capitalize Portal in developer portal, just thought it looked nicer. 
- Also made the gallery more responsive so it doesn't look …

[Fix]: fixes to images title for website loader, hotfix

---

hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
web/legacy/api/images/get_app_review_images.ts
web/legacy/api/images/graphql/getAppReviewImages.generated.ts
web/legacy/api/images/graphql/getAppReviewImages.graphql
web/pages/api/images/_get_app_review_images.ts

Let's reviewers see images awaiting review. Separate endpoint so we can have more granular permissions and since conditions are different. This seems cleaner

[Feat] Create an endpoint for reviewer to view images

---

web/scenes/Portal/Teams/TeamId/Apps/page/ClientPage/index.tsx

- Initial steps were moved -40px to top and it was blocking navigation on header
---
What was fixed:

fix: initial steps header overlap

---

hasura/metadata/databases/default/tables/public_user.yaml
web/components/LoggedUserNav/index.tsx
web/lib/utils.ts
web/scenes/Portal/Profile/common/UserInfo/index.tsx
web/scenes/Portal/Profile/common/graphql/client/fetch-user.generated.ts
web/scenes/Portal/Profile/common/graphql/client/fetch-user.graphql
web/scenes/Portal/Profile/page/index.tsx
web/scenes/Portal/Profile/types.ts
web/tailwind.config.ts

- This PR fixes empty name for the user logged in with `sign in with world id`. 
- Also fixes lightOrange color
‼️ I had to add permissions to user role to select world_id_nullifier, so it's a Hasura migration change
@andy-t-wang I don't really like current format of nullifier name. I'd prefer if it starts with truncated nullifier value to make it look more unique. Do you have any ideas?  
---

fix: add name for the nullifier users

---

web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/graphql/client/fetch-user-membership.generated.ts
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/graphql/client/fetch-user-membership.graphql
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/graphql/client/transfer-ownership.generated.ts
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/graphql/client/transfer-ownership.graphql
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/index.tsx

Transfer ownership previously would turn all the teams you're part of to admin. Thus if I was an owner on 2 teams and I transferred on 1 of them I would become admin on both of the teams.

Fix-transfer ownership

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/Kiosk/IDKitBridge/index.tsx

Turns out the previous change was inside the existing use effect hook so it wasn't being called on unmount. 
https://stackoverflow.com/questions/55020041/react-hooks-useeffect-cleanup-for-only-componentwillunmount

[Fix] Mount issues fix

---

web/pages/api/_ens.ts

Removing old addresses
We still have the start kit pulling the addresses from here. We should update those and then remove this endpoint https://github.com/search?q=org:worldcoin%20/v1/contracts&type=code

[fix] Remove deprecated addresses

---

web/components/Category/index.tsx
web/components/InitialSteps/Step/index.tsx
web/components/Link/index.tsx
web/components/LoggedUserNav/HelpNav/index.tsx
web/scenes/Onboarding/CreateTeam/page/Form/index.tsx
web/scenes/Portal/Profile/DangerZone/DeleteAccountDialog/index.tsx
web/scenes/Portal/Profile/Teams/page/List/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/ImageLoader/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/page/ClientPage/index.tsx
web/scenes/Portal/layout/CreateAppDialog/graphql/client/insert-app.generated.ts
web/scenes/Portal/layout/CreateAppDialog/graphql/client/insert-app.gql
web/scenes/Portal/layout/CreateAppDialog/index.tsx

People thought it was confusing since they both looked like buttons but one was disabled. I made it more explicit and removed category from create. We really want to accelerate making an app
- Also fix delete profile, wasn't logging you out previously
- Sign in with World ID had some weird formatting
- Cleaned up the onboarding in general to be much faster
- Fix the image loader to handle different sizes

[Fix] update quickstart

---

hasura/metadata/databases/default/tables/public_api_key.yaml
hasura/metadata/databases/default/tables/public_user.yaml
web/tests/integration/user.test.ts

Added a test case
https://linear.app/worldcoin/issue/WID-788/idor-vulnerability-allows-seeing-cross-team-user-information
Problem was that users could spoof team-id as it's just a header so we need to check user_id as well
- Fixed one other permission that was just not in line with the existing permissions

[Fix] Shouldn't be able to access a user from another team

---

web/Dockerfile

Fix image cache permission issue in datadog
⨯ Failed to write image to cache Mh8l5UFbTGA5nKOeFglEcL-ZNiLbLdYtN8O9Q+MaD8k= [Error: EACCES: permission denied, mkdir '/app/.next/cache/images'] {
Right now we create the .next file after we change ownership which is causing permission issues since permissions are assigned to the creator of the file and in this case it's root.

[Fix] fix for image caching

---

hasura/metadata/databases/default/tables/public_action.yaml
web/tests/integration/action.test.ts

Closes [WID-706](https://linear.app/worldcoin/issue/WID-706/team-members-can-edit-tos-and-privacy-policy-urls)
- Changes update permissions for user role on `action` table
- Adds tests
---
https://github.com/worldcoin/developer-portal/assets/89008845/736283e9-a230-46bc-93b9-85ef984dc3b3

fix: team members can edit tos and privacy policy urls

---

web/legacy/backend/verify.ts
web/tests/api/verify.test.ts

Updates `KNOWN_ERROR_CODES` to align with possible error codes from signup sequencer's `/verifySemaphoreProof` endpoint. Adds link to relevant error definitions.
Removes `rawCode` as it's unused.

chore: update errors from sequencer

---

web/legacy/lib/models.ts
web/pages/api/v1/oidc/token.ts

ensures the `nonce` value is included in the `id_token` returned during the authorization code flow

fix: include nonce in id_token for auth code flow

---

hasura/metadata/databases/default/tables/public_membership.yaml
hasura/metadata/databases/default/tables/public_team.yaml
hasura/migrations/default/1712070347860_create_get_team_owners_count_func/down.sql
hasura/migrations/default/1712070347860_create_get_team_owners_count_func/up.sql
web/tests/integration/membership.test.ts

Closes [WID-836](https://linear.app/worldcoin/issue/WID-836/idor-devportal-team-owners-can-delete-themselves-off-of-their-own-team)
This PR:
- Adds a `team_owners_count` computed field to the team table that counts a number of owners in the team. 
- Adds a restriction for the owner users to remove themselves from the team in case they are the only owner in the team. 
- Adds test for membership table

Fix owner delete

---

web/package.json
web/pnpm-lock.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/hook/use-image.tsx

Resizing the image was causing the file size to increase. The tradeoff then was that we either increase the file limit or remove resize. Given paolo had security concerns for increasing file size we will just remove automatic resizing. This is better behavior anyways since we have no idea what the file size will be after resizing.
We still let them upload different sizes that are compliant with our aspect ratio 
completes WID-855

[Fix] remove image resize

---

hasura/migrations/default/1712177502163_alter_table_app_rankings_constraint/down.sql
hasura/migrations/default/1712177502163_alter_table_app_rankings_constraint/up.sql
web/api/public/apps/index.ts
web/tests/api/public/apps.test.ts

Fix the ordering of rankings. Updated the tests to cover this. Previously only had one example so didn't notice that graphql was returning the apps out of order
Also added an enforcement that the platform and country has only one. I chose not to make a computed field here and upsert on it because the flow for making rankings should be that they first fetch the existing ranking. Thus we should know that there exists a ranking or not. And based on documentation if we know the column is not present we should not upsert

[fix] Ordering of rankings

---

web/lib/utils.ts
web/pages/api/v1/oidc/validate.ts
web/tests/api/utils.test.ts

Remove redundant `uriHasJS()` in favor of `validateUrl()` to improve consistency and prevent XSS issues

Add consistency to URL validation

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1712797451184_alter_table_public_app_metadata_add_column_world_app_button_text/down.sql
hasura/migrations/default/1712797451184_alter_table_public_app_metadata_add_column_world_app_button_text/up.sql
web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/public/app/[app_id]/index.ts
web/api/public/apps/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-metadata.graphql
web/api/public/apps/graphql/get-app-rankings.generated.ts
web/api/public/apps/graphql/get-app-rankings.graphql
web/api/public/apps/index.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/lib/utils.ts
web/pages/api/v1/precheck/[app_id].ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/graphql/client/update-app-links.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/graphql/client/update-app-links.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

- Add new field `world_app_button_text` that lets dev specify text they want show in the app default is use integration
- added new permission for reviewer role to update verified apps. This is set so we can remove apps from the app store via setting the `is_reviewer_app_store_approved` flag
- Add localise strings to platform=app
- Updated the return to include featured apps
- Update JSON to now parse the description when returning see spec for new format. 
- App and web return types are different
- Add the new button text field to links section
- Reduced world app description length to 35

API endpoint update

---

web/api/helpers/verify.ts

Handles inputs to proof verification shorter than 64 hex characters for `nullifier_hash`, `merkle_root`, `external_nullifier`, and `signal_hash`.
As these are all outputs of a hash function, there's no guarantee that the output is above a certain value, and we shouldn't expect to receive hex strings pre-padded.
This issue was identified during testing of an unrelated Android bug, where the `merkle_root` was valid, but only 63 hex characters long.
For the above-named inputs, this PR slices off `0x` from the string, pads the hex string with `0` up to 64 characters, and adds the `0x` back, then attempts to parse the hex string as a `uint256`.

fix: handle hex strings shorter than 64 characters (excluding 0x)

---

web/pages/api/v1/precheck/[app_id].ts

Required was blocking sign in with world id precheck causing things to fail. Removing required since we default to empty string

[Fix] precheck blocking empty string

---

web/api/prod/internal/v1/transactions/index.ts
web/lib/logger.ts

Lots of errors triggering on call alerts. i think this has to do with the upgrade to next js and the new endpoint
`Part terminated early due to unexpected end of multipart data` `Cannot read properties of undefined (reading 'remoteAddress')`
Header one was cause of this https://app.datadoghq.com/logs?query=env%3Aproduction%20app%3Adeveloper-portal%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY9OGcXSNrkiQgAAAAAAAAAYAAAAAEFZOU9HY2lGQUFCSElScGxhNDJWQ3dBQQAAACQAAAAAMDE4ZjRlMjYtOGI1ZS00N2QxLThhN2YtN2ZiMzMxMWI1OGE5&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1715002035421&to_ts=1715016435421&live=true
I can't tell where it's coming from since our log traces are bad

[Fix] Dev portal next js migration errors

---

web/legacy/backend/verify.ts

Somehow ians changes got reverted. This handles cases when values are not 66 characters long

[Fix] Hex padding

---

web/api/v2/minikit/transaction/[transaction_id]/graphql/fetch-api-key.generated.ts
web/api/v2/minikit/transaction/[transaction_id]/graphql/fetch-api-key.gql
web/api/v2/minikit/transaction/[transaction_id]/route.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts
web/tests/api/v2/minikit-transaction.test.ts

This endpoint is used by web2 apps to confirm the transaction was successfully mined on chain. Developers will use their api key in the dev portal in order to call this endpoint. Developers will only be able to see transaction data for apps that they own the API key for. 
Developers will call this via `developer.worldcoin.org/v1/minikit/transactions/transaction_id?app_id=12312`.
Upon successful completion this will return a singular transaction object back to the user in the form of 
[transaction_data]

Feat: Transaction Endpoint for Mini Apps

---

hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_action.yaml
hasura/metadata/databases/default/tables/public_nullifier.yaml
web/legacy/api/images/get_app_review_images.ts
web/legacy/api/images/get_unverified_images.ts
web/legacy/api/images/get_uploaded_image.ts
web/legacy/api/images/upload_image_url.ts

Currently Hasura actions are GET requests but they contain body. This is casuing datadog to spasm for good reason. I will move them to GET requests but we should do that when migrating the endpoints out of legacy. This is a temp fix for now to make them post requests.

Fix: Hasura Actions GET -> POST

---

web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/graphql/client/fetch-keys.generated.ts
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/graphql/client/fetch-keys.graphql
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/layout/index.tsx

Previously we were not filtering keys by team such that you could see keys for other teams that you were part of

Fix: Update view permissions and filter keys

---

web/legacy/api/_invite-team-members/graphql/fetchInvites.generated.ts
web/legacy/api/_invite-team-members/graphql/fetchInvites.gql
web/legacy/api/_invite-team-members/graphql/getUserAndTeamMemberships.generated.ts
web/legacy/api/_invite-team-members/graphql/getUserAndTeamMemberships.graphql
web/legacy/api/_invite-team-members/index.ts
web/scenes/Portal/Teams/TeamId/Team/page/Members/InviteTeamMemberDialog/index.tsx

This should fix the invites bug when you have incorrect behavior if you invite the same email to different teams. 
Problem: 
- Logic is so that if a user sends an email that is already in the invite list we should just update the existing one instead of creating a new one with the same email. 
- The issue was the condition that filters existing emails. The condition didn't check the `teamId` and as a result, if you already have an invite to team A, when you try to create an invite to team B, an invite to team A will be selected as an "invite to update", but not as an "invite to create".
PR also fixes incorrect team names in the invite email
---
Screencast updated:
https://github.com/worldcoin/developer-portal/assets/89008845/92752b3f-f089-4205-bb71-4f64a6a8dad6

fix: invite same email to the multiple teams

---

web/app/(portal)/kiosk/[appId]/[actionId]/page.tsx
web/scenes/Portal/Kiosk/index.tsx

Creates a kiosk page that can be shared at a static URL, and is compatible with Apple's "Add to Home Screen" functionality.
Primary purpose is to support kiosks on iPads.

feat: static kiosk link

---

web/pages/api/v1/graphql.ts

We are firewall blocking requests now, so we should have a pass through of valid authorization headers. Currently if someone has a valid JWT for the service or reviewer role they are hitting hasura directly. We are changing access to now not allow public access so they will need to go through this api

Fix: Pass through of API keys

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/metadata/databases/default/tables/public_app_reviews.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1718063882069_create_table_public_app_reviews/down.sql
hasura/migrations/default/1718063882069_create_table_public_app_reviews/up.sql
web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-metadata.generated.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts

This PR adds the hasura migration and permissions for app rating
- Creates the new `app_reviews` table
- Adds a computed field `app_rating` to `app_metadata`
- Adds permissions for service role to modify and read the value
- Add permission for service role to insert new app_ratings as well as update the rating

WID-1047 Hasura Backend Changes for App Rating

---

web/api/v2/public/app/[app_id]/index.ts
web/lib/constants.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps-metadata.test.ts

App endpoint for v2 has native apps that we change the `app_id` for. This improves the test coverage for this case as well as makes it able to handle passing in the subbed app_id since the app won't know the actual app_id

Improve native app endpoint

---

web/api/helpers/jwks/index.ts
web/api/helpers/jwts.ts
web/api/helpers/kms.ts
web/legacy/backend/jwks.ts
web/legacy/backend/jwts.ts
web/legacy/backend/kms.ts
web/tests/api/__mocks__/kms.mock.ts
web/tests/api/oidc/authorize.test.ts
web/tests/integration/oidc/token.test.ts

Updates JWTs used in Sign In with World ID to use PS256 instead of RS256 for signing. No changes made to key generation logic, as both RS256 and PS256 use RSA keys. Must be tested in staging before deploying to production.
Not intended to impact Hasura JWT authentication.

feat: switch from RS256 to PS256 for OIDC JWT

---

web/api/v2/app/submit-app-review/index.ts
web/lib/hashing.ts
web/lib/utils.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps-metadata.test.ts

Right now the app cannot generate external nullifiers. We could add the logic to oxide but this is a one off instance and we need to do that in wallet kit anyways. External nullifier is not a secret value and can be calculated so it's fine to just return it in the directory

Add Ratings External Nullifier to App Directory

---

docker-compose-test.yaml
hasura/metadata/databases/default/tables/public_action.yaml
web/tests/integration/action.test.ts

We don't have a restriction on deletion for sign in with world id. This fixes that. While this security wise doesn't cause an impact it does create a functionality bug where if you delete the sign in action then the page wont' load

Disable Delete Sign in Action

---

web/api/hasura/invalidate-cache/index.ts

Invalidate cache paths requires the * to invalidate query params as well

cache paths

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx

Previously the support link would not go to null if you toggled between the approve and original version which was visually confusing

small improvement to links

---

web/components/CopyButton/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ApiKeyRow/index.tsx

Improves the api keys flow. Makes it so it's clear you need to reset the key and also makes it easier to find the keys by adding to top nav since we are using api keys more now

Improve api keys

---

web/api/v2/app/submit-app-review/index.ts

I believe staging is using staging environment. There's no need to use staging if the app_id is staging for the app review

fix rating

---

web/lib/languages.ts

Android is sending a hyphen instead of an underscore

Fix localisation

---

web/pages/api/v1/oidc/token.ts
web/tests/integration/oidc/token.test.ts

Uses one atomic GraphQL mutation to return and delete the `auth_code` when accessing the OIDC `/token` endpoint.
completes sec-697
Not yet tested.

fix: prevent OIDC /token endpoint race condition

---

web/pages/api/v1/oidc/authorize.ts

Allows null/undef/empty `nonce` for auth code flow in Sign In with World ID.

fix: allow null/undef/empty nonce for auth code flow

---

web/scenes/Onboarding/Login/page/index.tsx

- Login page not rendering for some reason
- This is a temp fix that will open auth0 provider instead of login page if getSession fails. This is the only potential place where it fails, as I can see.
- Adds logging on getSession error

temp login page fix

---

web/pages/api/v1/oidc/validate.ts

Check the sign in ip since the sign in server is getting rate limited by our blanked rule. We will add an exception for it so it doesn't go down during high usage like with DSCVR this past week

Temp check sign in ip

---

web/next.config.mjs

My understanding is that we dont actually need this header and it's causing issues when we try to remove cors restrictions on certain endpoints

Remove Header

---

web/api/helpers/verify.ts
web/legacy/backend/verify.ts

From the protocol team:
> We should also remove the explicit use of status field from the response and rely on HTTPS status codes.

remove use of status in sequencer response

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/getAccumulativeTransactionData.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/StatCards/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/server/index.ts

This fixes two things, first of all the transaction amount is in USD and had 3 decimals, rounded to 2 now.
Secondly, switched up the default dashboard selector from all time to weekly. All time new users = all time users (we already show that), so maybe let's show meaningful data? The drawback is a smaller number...

Fix new users stat

---

hasura/migrations/default/1731651264113_create_index_app_id_index/down.sql
hasura/migrations/default/1731651264113_create_index_app_id_index/up.sql

App rating field is horribly expensive right now, that's what's causing the CPU usage errors

Optimize app_rating field

---

web/components/TextArea/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

arrows allow to switch left to right & vice versa, wrapping from last to first & vice versa
on top of that they indicate that there's some switching to be done - users will hopefully instinctively know how localisations work
edit: Most importantly, localisations are now saved between switches, so no data loss

fix: add localisation arrows, save on change

---

web/api/v2/verify/index.ts

improve error logging, noisy logs currently
To investigate this: https://app.datadoghq.com/logs?query=env%3Aproduction%20service%3Aworldcoin-developer-portal%20-cluster_name%3Adeveloper-portal-pipeline-hasura-hasuraclusterd2778a7c-qeizo5436rd1%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZM7AEZw6iDNPgAAABhBWk03QUVnV0FBRDJ1T01BVm5zcUVBQUEAAAAkMDE5MzNiMDItYTg4MS00NWEwLWJmNDctYTdmMjIwYjVkOGQ3ABCEKw&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=1082985022758335922&storage=hot&stream_sort=desc&viz=stream&from_ts=1731805845396&to_ts=1731892245396&live=true

Improve error logging

---

web/lib/utils.ts

Added an early return to tryParseJson so that we don't get a bunch of warns
tests fail bc of previous PR

tryParseJson returns early if nil

---

web/lib/utils.ts

early return if nil or empty string

fix: prevent excessive warns

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Transaction errors should check if res is ok first before parsing so we get cleaner failures

Fix Transaction Errors

---

web/api/helpers/app-store.ts
web/lib/types.ts
web/tests/api/v2/minikit-app-metadata.test.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

Add impressions to metadata

---

web/@types/global.d.ts
web/api/helpers/app-rating/index.ts
web/instrumentation.ts
web/jest.setup.ts
web/next.config.mjs
web/pages/api/v1/oidc/authorize.ts
web/tests/api/oidc/authorize.test.ts
web/tests/integration/oidc/authorize.test.ts

This PR adds redis client usage with instrumentation file.
Instrumentation file docs: 
https://nextjs.org/docs/app/api-reference/file-conventions/instrumentation
Shortly (but read the doc), we use `register()` inside the instrumentation file to execute Redis client creation only once on the application starting after the build. Then, we store the Redis client instance globally to access it everywhere. 
- PR is not finished. We should apply global client everywhere where we are using redis client.

add instrumentation file

---

hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
web/api/hasura/tmp-insert-app-report/graphql/create-app-report.generated.ts
web/api/hasura/tmp-insert-app-report/graphql/create-app-report.graphql
web/api/hasura/tmp-insert-app-report/index.ts
web/app/api/hasura/tmp-insert-app-report/route.ts

This is needed so that there aren't any interruptions in the app reporting flow. Other PR introduces breaking changes, which would result in rejected inserts. This ensures that reports always go through in the transition period

fix: provide compatibility layer for report form

---

web/lib/schema/index.ts

allow % for descriptions and such, requested by a few builders

fix: add % to long form text regex

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Improve error response so devs know what they're receiving

Improve error response

---

web/api/v2/public/app/[app_id]/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/QrQuickAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/index.tsx
web/tests/api/v2/public/apps/app.test.ts

This PR:
- Add support `app_metadata_id` query param in `/public/app/{app_id}` endpoint.
- Update QR code action to include `app_metadata_id`  used for deeplinking
- Add a warning message for draft version qr code/urls
Wait for mobile work to suport these changes, otherwise the warning message above the QR code will confuse developers.

DEV 1261: Support app metatada id in deeplinking and public app endpoint

---

web/api/v2/minikit/send-notification/graphql/fetch-metadata.generated.ts
web/api/v2/minikit/send-notification/graphql/fetch-metadata.graphql
web/api/v2/minikit/send-notification/index.ts
web/tests/api/v2/send-notification.test.ts

Allow an unverified app to send notifications up to 40 per 4 hours to do testing

Allow unverified apps to test notifications

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

await the refetch to prevent showing stale data - if for example going english -> spanish -> back to english the form could show stale english translation

fix: en lang refetch

---

web/components/Category/index.tsx
web/components/Input/index.tsx
web/components/SelectMultiple/index.tsx
web/components/TextArea/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/MaxVerificationsSelector/index.tsx

Visual bug on safari where these values were wrapping and making the fields look bad

Fix visual bug on safari

---

web/api/v2/public/apps/index.ts

This will cause CloudFront to serve cached data, when developer portal returns an error. Even if it's after ttl
To test I guess the easiest would be to block prod transition, merge this, invalidate cache, merge another PR that makes this error always and see if CF serves it correctly. Let's coordinate this on merge @andy-t-wang

Cloudfront cache

---

web/Dockerfile

https://github.com/nodejs/corepack/pull/614
https://github.com/stackblitz-labs/bolt.diy/issues/1250
Default corepack version was failing due to signature verification.
Pinned a working corepack version to fix docker build  GH Action.

Set working corepack version to fix docker CI

---

web/api/v2/public/app/[app_id]/index.ts

This is exactly what i did in public/apps, as in it will return stale cached data from cloudfront if developer portal errors

fix: return cache if error for individual apps too

---

web/api/v2/public/app/[app_id]/index.ts
web/lib/types.ts
web/tests/api/v2/public/apps/app.test.ts

This PR adds `draft_id` to `/app` endpoint. It only does this if the respective app has draft metadata based on the `draft_id` query param.

Add `draft_id` to response

---

web/api/v2/public/apps/index.ts
web/tests/api/v2/public/apps/apps.test.ts

When requesting this from server side, there's no way to specify the correct country (to filter out apps). This adds a query param that allows a country code to be specified (ISO 3166-1 alpha-2)

fix: add an optional country param

---

web/api/v2/public/apps/index.ts

Country param was an old param we deprecated since it wasn't performant on mobile. Seems like we still send it sometimes which causes the app store list to be incorrect.

Override country

---

.gitignore
README.md
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_action.yaml
hasura/migrations/default/1739394725314_alter_table_public_action_add_column_webhook_uri_pem/down.sql
hasura/migrations/default/1739394725314_alter_table_public_action_add_column_webhook_uri_pem/up.sql
web/.env.test
web/components/Input/index.tsx
web/components/Toggle/index.tsx
web/graphql-codegen.schema.js
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/package.json
web/pages/api/v1/precheck/[app_id].ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/graphql/client/get-kiosk-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/graphql/client/get-kiosk-action.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/graphql/client/update-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/graphql/client/update-action.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/AppFlowOnCompleteTypeSelector/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/FlowTypeSelector/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/graphql/server/insert-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/graphql/server/insert-action.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/server/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.graphql

* Add support for configuring a webhook, associated with an action.
* `webhook_uri` and `webhook_pem` added to the existing action table.
* Updated the preflight gql query to include both fields.
* The webhook must have a corresponding RSA public key PEM.
* The `webhook_uri` and `webhook_pem` are biconditional dependencies, meaning they either both exist or both don't exist. As such, I've added validations to the create and update actions to ensure that this remains true, with appropriate error messages.
* I've manually tested this in a local dev environment (some screenshots attached).

Add webhook configuration to incognito actions config.

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

now compares category lowercase
also before returning checks whether all apps have a valid category

remove external category properly

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

it's expected when calling from the app as we don't show external
Doesn't break the app, because we're still not returning anything, but sends a more correct res code

invalid category results in a 404 now

---

web/lib/constants.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/server/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/server/form-schema.ts

Our tests need to be able to make local calls (e.g. to an endpoint like `/internal/test`) which the previous config did not allow for. This fixes that, and also allow-lists our E2E test team.
Tested locally.

Update webhook validation for E2E test config

---

web/api/v2/public/apps/index.ts
web/lib/compare-versions.ts
web/lib/compare-versions.unit.spec.ts
web/lib/constants.ts
web/tests/api/v2/public/apps/apps.test.ts

we'll have contacts as a new native miniapp. this pr adds app_id mappings, and version filtering as we want to show the app only above a certain version

new mappings, version filtering logic in /apps

---

web/api/v2/public/apps/index.ts
web/tests/api/v2/public/apps/apps.test.ts

we were filtering the contacts miniapp based on "contacts" as app_id, but we should use the actual id, not mapped one
tests reflect that as well now

filter out based on actual id not mapped one

---

hasura/Dockerfile

This reverts commit 5102985cf4e4899eb2813c6fee213a1161caa521.
Reverts the Hasura docker image to the one from the public registry.

fix: Revert "Get Hasura docker image from AWS public ECR (#1294)"

---

hasura/Dockerfile

Bumps the Hasura image version to `v2.47.0.cli-migrations-v3` and increases the server timeout to 3600 seconds.

fix: Bump hasura image version

---

docker-compose-test.yaml
docker-compose.yaml
hasura/migrations/default/1745259204240_reset_invalid_fields/up.sql
hasura/migrations/default/1745259377078_is_android_only_default_false/down.sql
hasura/migrations/default/1745259377078_is_android_only_default_false/up.sql

Ticket - [DEV-1621](https://linear.app/worldcoin/issue/DEV-1621/[mobile]-fix-migrations-android-only-flag-needs-to-default-to-false)
Adds a migration to clean up the invalid URLs in the app_metadata table.

fix: Add clean up migration

---

web/api/helpers/app-store.ts

important changes:
before normalizing data, filter the miniapp statistics dataset to include only apps present in the app store (different across countries)
then, filter with 0.3 weight given to total unique users and 0.7 given to new users in past 7 days
For the US app store, this yields the following top 30 miniapps (with default pinned apps removed)
```
Humans vs AI
Cash Convert
UNO
ORO
Cash Daily
ORB
World Republic
Farcade
Claim $MINI Daily
DNA Wallet
Eggs Vault
THE BOX
World Chat Beta
ASTRACOIN
AION
PoolTogether
AXO
Golden Otter Hub
Sage
BitMaster
DNA GenomeX
EarnOS
PUF
Add Money
Crypto Merge
DNA
GalAxo
Golden Otter Maze Game
LOCO
Diamond Rush
```

alter the sorting algorithm

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/layout/index.tsx

App store copy is really confusing. We are allowed to use App store if it's not in reference to the Apple App Store

Make app store copy less confusing

---

web/api/v2/public/app/[app_id]/index.ts

app shouldn't be cleared from home screen when set to android only. existing users should still be able to access.
This change leaves app store filtering, so the app won't be listed, but will be deeplinkable and accessible to users

remove platform check from single get endpoint

---

web/api/helpers/verify.ts
web/tests/api/helpers/verify.test.ts

Addresses issue #2 from [DEV-1748](https://linear.app/worldcoin/issue/DEV-1748/h1-users-can-validate-zkps-many-times-in-devportal-due-to-case)

DEV-1748: Fix nullifier hash prefix vulnerability

---

hasura/metadata/databases/default/tables/public_nullifier.yaml
hasura/migrations/default/1747818197472_alter_table_public_nullifier_add_column_nullifier_hash_int/down.sql
hasura/migrations/default/1747818197472_alter_table_public_nullifier_add_column_nullifier_hash_int/up.sql
web/api/helpers/verify.ts
web/api/v1/oidc/authorize/index.ts
web/api/v2/verify/graphql/atomic-upsert-nullifier.generated.ts
web/api/v2/verify/graphql/atomic-upsert-nullifier.graphql
web/api/v2/verify/index.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/tests/api/helpers/verify.test.ts

This PR adds `nullifier_hash_int` column to store the integer representation of the hex `nullfier_hash`, this will improve security solving case sensitive, padding issues we have.

DEV-1748: Add nullifier int column 

---

hasura/migrations/default/1747841041612_run_verification_trigger_only_when_uses_column_updates/down.sql
hasura/migrations/default/1747841041612_run_verification_trigger_only_when_uses_column_updates/up.sql

This allows us to update `nullifier_hash_int` column, for rows that have invalid/corrupt uses.

Update verification trigger to run only when `uses` column is updated

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

Ticket - [DEV-1723](https://linear.app/worldcoin/issue/DEV-1723/h1-admin-role-can-permanently-lock-out-team-owner-and-newly-invited)
Deletes the ADMIN and OWNER user permissions to delete app metadata, as there is no use-case for them on the frontend.

fix: Remove user permissions to delete app metadata

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/server/index.ts

add a single value stat to notification chart
update chart colors, so that old ones match the legend, and notification chart doesn't collide with old ones. Opt-in rate is a single value not a time series so added it as an additional stat, seemed to fit in alright. 
Once we get more related 1 value stats i'll move it out to a new section/component

Add notif opt in rate stat

---

web/api/v2/verify/index.ts
web/tests/integration/api/v2/verify.test.ts

Improve error codes by returning `400` instead of `500` when nullifier hash is invalid hex.

Handle gracefully invalid nullifier hash

---

web/lib/opensearch.ts

Fixes the OpenSearch query performance issue by replacing the `must` clause with a `filter` clause (which is cached).

fix: Replace must with filter in OpenSearch

---

hasura/metadata/databases/default/functions/public_increment_app_stats.yaml
hasura/metadata/databases/default/tables/public_app_stats.yaml

Adds missing service permissions to the `public_app_stats` table in the Hasura metadata.

fix: Add missing service permissions

---

web/api/v2/verify/index.ts

This PR adds a warning logs for invalid JSON logs in `/verify`, to monitor close

Log invalid JSON bodies in `/verify`

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

Deleted apps should not be returned to home-screen
- introduces new `show_deleted` flag
- changes endpoint behavior to return a 404 when metadata is deleted, unless this new flag is present and true
- adds tests for this behavior

flag to return a deleted app instead of 404

---

web/api/hasura/invalidate-cache/index.ts
web/api/helpers/fetch-metrics.ts
web/api/v2/public/apps/index.ts

Fetch metrics currently returns a huge list of data. 
This implementation changes the logic to such
1. We do a single call to the metrics service that calculates the data for each country and global. The data is then cached in memory for 10 minutes.
2. Any requests that come in while this call is in progress will await the call. 
3. If there is already data in the memory cache we will return that immediately. 
Upon invalidating cache we also clear the memory cache as this is what we'd expect when invalidating on the retool side to get fresh rankings

Refactor v2 of Fetch Metrics

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/lib/utils.ts

Ticket - [DEV-2098](https://linear.app/worldcoin/issue/DEV-2098/dev-portal-investigate-504-errors-in-get-transaction)
Adds a timeout of 3 seconds to internal transactions request and introduces a retry mechanism for it.

feat: Add timeout and retry logic to transactions request

---

web/api/helpers/fetch-metrics.ts
web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/api/v2/public/app/[app_id]/index.ts
web/lib/utils.ts

If timeout is specified in the fetch options, it's used only once. All subsequent requests time out instantaneously. 
This PR creates a timeout object for each request.

fix: Introduce timeout parameter to avoid using same options object

---

web/api/v2/minikit/send-notification/index.ts
web/lib/utils.ts

Removes retry logic for the `/send-notification` endpoint, leaving only timeout.

fix: Remove retry logic for send notification

---

.github/workflows/ci-app-router.yml

End-to-end tests are sometimes failing due to setup timeout. Seems like a lag caused by lack of system resources (CPU/RAM).
Temporarily added a better GitHub-hosted runner to see if this is the case.

CORPLAT-370 Use better runner for end-to-end tests

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/index.tsx

fixes a bug where when a user creates a brand new app, fills out all fields and tries to submit for review, they get an error.
This is because the validator expects en data (name, short name etc.) in the top level, not nested in localizations array only
saving & refreshing the page fixes this bug

pass en localization data to final validator

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/stat.tsx

- currently, the label at the top of the chart shows the last entry in metrics list
- this could result in it being 0, even though users may expect an average instead
- show average notification open rate always, instead of last value
- if there's less than 7 days of data, don't show the badge eligibility icon
- if there's more than 7 days of data, show the icon
The above is in line with app-backend logic - it checks `avg_notification_open_rate` on metadata, which is only set if more than 7 days of data is present

improve open rate chart displays

---

web/lib/permissions/graphql/server/get-team-update-permissions.generated.ts
web/lib/permissions/graphql/server/get-team-update-permissions.graphql
web/lib/permissions/index.ts

Ticket - [DEV-2163](https://linear.app/worldcoin/issue/DEV-2163/h1-access-control-on-developerworldcoinorg)
Restricts the team name update operation to the OWNER role.

feat: Restrict team name update to OWNER

---

hasura/metadata/databases/default/tables/public_nullifier.yaml

Delete app stats trigger since it creates high load on the DB.

fix: Delete app stats trigger

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

The backend DB is having downtime spikes and each time the retries bombard the backend with requests and make it harder for the server to recover. Reduce retry count

fix: transaction endpoint is hammering backend
