.github/workflows/deploy-staging.yml

Only modifies the staging workflow, by merging steps.

ci: Merge deployment and migration steps in staging

---

web/common/Button/index.tsx
web/common/Header/index.tsx
web/common/HeaderText/index.tsx
web/common/Switch/index.tsx
web/logics/actionLogic.ts
web/scenes/action/ActionHeader/index.tsx
web/scenes/action/Deployment/Interface/index.tsx
web/scenes/action/Deployment/index.tsx
web/scenes/action/action.tsx

https://user-images.githubusercontent.com/89008845/194274708-e241025a-95ac-4cb1-a6f0-eda78f955426.mp4

refactor: update deployment form logic

---

infrastructure/package.json
infrastructure/src/data/index.ts
infrastructure/yarn.lock

Export database security group id and credentials secret arn. These are used to setup synchronization via DMS.

chore: export database secret and security group

---

infrastructure/src/hasura/index.ts

Only fixes the value in the settings.

chore: Fix the default value in config

---

infrastructure/src/hasura/index.ts

chore: Bump Hasura version v2.10.0

---

infrastructure/.env.example
infrastructure/src/hasura/parameters/dev.ts
infrastructure/src/hasura/parameters/production.ts
infrastructure/src/hasura/parameters/staging.ts
infrastructure/src/web/index.ts
infrastructure/src/web/parameters/dev.ts
infrastructure/src/web/parameters/production.ts
infrastructure/src/web/parameters/staging.ts

- Make two separate scaling configs for web & hasura stacks.

chore: split hasura & web scaling configs

---

web/api-helpers/cors.ts
web/pages/api/v1/oidc/authorize.ts

fix: real fix

---

web/src/components/Button/index.tsx

<details><summary>Result</summary>
</details>

fix: common button className misposition

---

web/src/components/Layout/temp-data.ts
web/src/scenes/sign-in-with-world-id/Credentials/index.tsx
web/src/scenes/sign-in-with-world-id/index.tsx
web/src/scenes/sign-in-with-world-id/store/index.ts

<details><summary>Result</summary>
https://user-images.githubusercontent.com/102026658/223414043-fc31d1c7-9b37-4090-9c31-9bfbc0c1f04e.mov
</details>

feat: signin reset token

---

web/src/pages/_app.tsx
web/src/scenes/actions/Action/ActionHeader.tsx

fix: empty state for actions

---

web/src/scenes/actions/index.tsx

[WID-382](https://linear.app/worldcoin/issue/WID-382/fix-docs-link)

fix: docs link

---

web/src/backend/oidc.ts
web/src/backend/verify.ts
web/src/pages/api/v1/precheck/[app_id].ts
web/src/pages/api/v1/verify/[app_id].ts

Closes [WID-384](https://linear.app/worldcoin/issue/WID-384/additional-checks-on-precheck-verify-oidc)

refactor: add action status check

---

web/src/hooks/useApps.ts
web/src/scenes/app/RemoveAppDialog/index.tsx
web/src/scenes/app/index.tsx
web/src/stores/appStore.ts

[WID-385](https://linear.app/worldcoin/issue/WID-385/delete-app-button-is-missing)

feat: add delete app button

---

web/src/hooks/useSignInAction.ts
web/src/scenes/sign-in-with-world-id/Redirects/index.tsx

[WID-383](https://linear.app/worldcoin/issue/WID-383/fix-redirect-url-inputs-on-sign-in-page)
https://user-images.githubusercontent.com/104859710/224718473-01787581-cd75-4530-944a-b17cd592b1f4.mp4

fix: saving redirects

---

web/.eslintrc.json
web/src/components/FieldTextArea/index.tsx
web/src/components/Layout/NewAppDialog/EngineSwitch/index.tsx
web/src/components/Layout/NewAppDialog/index.tsx
web/src/hooks/useApps.ts
web/src/pages/_app.tsx

Added "new app" logic
<details><summary>Result</summary>
https://user-images.githubusercontent.com/102026658/224695246-b2ea0fc2-a6cb-4639-b08b-3b49b7907696.mov
</details>

feat: new app logic

---

web/src/scenes/team/Details/index.tsx
web/src/scenes/team/MemberList/index.tsx
web/src/scenes/team/team.tsx

- Removed "My Team Details" label
- Fixed padding between blocks
<details><summary>Result</summary>
</details>

fix: team page fixes

---

web/src/scenes/actions/Action/index.tsx

The shadow is drastically reduced, but returns when opening or hovering.
https://user-images.githubusercontent.com/104859710/224818803-fa9a8f57-2b12-4ede-8797-8be80f5dc286.mp4

style: reduce shadow

---

web/src/components/Layout/NewAppDialog/index.tsx
web/src/components/Switch/index.tsx
web/src/hooks/useApps.ts

Related to [Slack thread](https://ottofeller.slack.com/archives/C03MN2BP61J/p1678809811553829)
- Add `is_staging` switcher to `add new app` modal
- Adjust height of modal
---
https://user-images.githubusercontent.com/89008845/225084515-f49e8cc6-b14a-4a3c-adde-0d8f3660f86e.mp4

feat: add staging/production switcher

---

web/src/components/Layout/AppSelector/index.tsx
web/src/scenes/app/Stats/index.tsx

https://user-images.githubusercontent.com/89008845/227373293-1b654d91-3aa8-401d-8df7-543ef2310e68.mp4

fix: App page fixes

---

web/src/components/Auth/index.tsx
web/src/scenes/login/login.tsx

updated auth layout, fixed horizontal scroll on login page

fix: remove horizontal scroll on login page

---

web/src/components/Layout/NewAppDialog/EngineSwitch/Option/index.tsx
web/src/components/Layout/NewAppDialog/EngineSwitch/index.tsx
web/src/components/Layout/NewAppDialog/index.tsx

https://user-images.githubusercontent.com/89008845/227381646-fdcabffc-3e02-4c97-886c-588a3a9e7fbb.mp4

refactor: new app modal update

---

web/src/scenes/team/MemberList/Controls/index.tsx
web/src/scenes/team/MemberList/InviteMembersDialog/index.tsx

feat: enable team invitation button with temporary message

---

web/src/hooks/useActions.ts
web/src/scenes/actions/Action/ActionHeader.tsx
web/src/scenes/actions/Action/VerificationBadges.tsx
web/src/scenes/actions/Action/index.tsx
web/src/scenes/actions/NewAction/index.tsx
web/src/stores/actionStore.ts

Imo, should rethink the custom action UI.  This is slightly better

fix: modify max verifications for custom actions

---

web/src/components/Layout/AppSelector/index.tsx

https://user-images.githubusercontent.com/104859710/227539290-72ebe43d-9597-4bdb-9ff4-146711c2f416.mp4

fix: update app selector url formatter

---

web/src/components/Layout/NewAppDialog/index.tsx

https://user-images.githubusercontent.com/89008845/227578483-5dbb4abd-794a-4aef-a44c-fb1fa7c47bac.mp4

fix: new app form validation

---

web/public/icons/stats.svg
web/src/components/Icon/index.tsx
web/src/scenes/app/Stats/index.tsx

https://user-images.githubusercontent.com/89008845/227600419-5d614df1-896e-49c0-aad9-2033384e4aea.mp4

refactor: add no data state for stats

---

web/src/scenes/actions/index.tsx
web/src/scenes/sign-in-with-world-id/index.tsx

fix: app not found state

---

web/src/components/Layout/index.tsx
web/src/lib/urls.ts

fix: app url

---

web/src/scenes/team/team.tsx

the current user was not passed to the layout on the team page, now it is passed

fix: user visibility on the team page

---

web/src/pages/api/login.ts
web/src/pages/api/v1/debugger.ts

- Fixes debugger, error cases were not working.
- Removes ETHTokyo invite code.

feat: fix debugger & post tokyo

---

README.md

Updates README with instructions for KMS, dev login, and more

chore: update README with dev instructions

---

README.md
web/src/pages/api/login.ts

Adds temporary invite code for ETHLisbon

feat: invite code for eth lisbon

---

web/src/backend/verify.ts
web/src/lib/constants.ts
web/src/lib/types.ts
web/src/lib/utils.ts
web/src/pages/api/v1/clients/inclusion_proof.ts
web/src/pages/api/v1/clients/insert_identity.ts
web/src/pages/api/v1/debugger.ts
web/src/pages/api/v1/oidc/authorize.ts
web/src/pages/api/v1/verify/[app_id].ts
web/src/scenes/debugger/Result/index.tsx

Allows simulator to perform proof verifications against Optimism staging sequencer

feat: add verification against optimism

---

web/src/lib/send-email.ts
web/src/pages/api/_invite_team_members.tsx
web/src/pages/api/login-with-invite.ts
web/src/pages/login-with-invite.tsx
web/src/scenes/login-with-invite/index.tsx

feat: use SendGrid templates

---

web/src/pages/api/signup.ts

This properly fixes the `nullable` emails

fix: proper sign up fix

---

hasura/metadata/databases/default/tables/public_auth_code.yaml
hasura/migrations/default/1691608768776_alter_table_public_auth_code_add_column_code_challenge/down.sql
hasura/migrations/default/1691608768776_alter_table_public_auth_code_add_column_code_challenge/up.sql
hasura/migrations/default/1691608790474_alter_table_public_auth_code_add_column_code_challenge_method/down.sql
hasura/migrations/default/1691608790474_alter_table_public_auth_code_add_column_code_challenge_method/up.sql

- Add `code_challenge` field to `auth_code` table
- Add `code_challenge_method` to `auth_code` table
- Add permissions to insert, select these fields for service role
---

feat: add code_challenge & code_challenge_method fields to auth_code table

---

hasura/metadata/databases/default/tables/public_action.yaml
hasura/metadata/databases/default/tables/public_redirect.yaml
hasura/migrations/default/1694731348594_alter_table_public_action_add_column_privacy_policy_uri/down.sql
hasura/migrations/default/1694731348594_alter_table_public_action_add_column_privacy_policy_uri/up.sql
hasura/migrations/default/1694731364313_alter_table_public_action_add_column_terms_uri/down.sql
hasura/migrations/default/1694731364313_alter_table_public_action_add_column_terms_uri/up.sql
web/package.json
web/pnpm-lock.yaml
web/src/graphql/graphql.schema.json
web/src/graphql/graphql.ts
web/src/hooks/useSignInAction.ts
web/src/lib/models.ts
web/src/pages/api/v1/oidc/register.ts
web/src/pages/api/v1/precheck/[app_id].ts
web/src/scenes/sign-in-with-world-id/Redirects/RedirectInput/index.tsx
web/src/scenes/sign-in-with-world-id/Urls/UrlInput/index.tsx
web/src/scenes/sign-in-with-world-id/Urls/index.tsx
web/src/scenes/sign-in-with-world-id/index.tsx

- added inputs to the Sign in with Worldcoin config page
- added attributes to the registration endpoint
- corrected precheck api route handler

feat: allow input terms and privacy policy for action

---

web/src/hooks/useSignInAction.ts
web/src/scenes/sign-in-with-world-id/Redirects/RedirectInput/index.tsx
web/src/scenes/sign-in-with-world-id/Redirects/index.tsx
web/src/stores/signInActionStore.ts

- now an empty redirect is not saved in the database
- a message about adding a redirect is displayed
https://github.com/worldcoin/developer-portal/assets/104859710/4062307f-a93c-4ef3-972d-358a4595efba

feat: improve redirect adding

---

hasura/metadata/databases/default/tables/public_action.yaml
hasura/metadata/databases/default/tables/public_redirect.yaml
hasura/migrations/default/1694731348594_alter_table_public_action_add_column_privacy_policy_uri/down.sql
hasura/migrations/default/1694731348594_alter_table_public_action_add_column_privacy_policy_uri/up.sql
hasura/migrations/default/1694731364313_alter_table_public_action_add_column_terms_uri/down.sql
hasura/migrations/default/1694731364313_alter_table_public_action_add_column_terms_uri/up.sql
web/pnpm-lock.yaml
web/src/graphql/graphql.schema.json
web/src/graphql/graphql.ts
web/src/hooks/useSignInAction.ts
web/src/lib/models.ts
web/src/pages/api/v1/oidc/register.ts
web/src/pages/api/v1/oidc/token.ts
web/src/pages/api/v1/precheck/[app_id].ts
web/src/scenes/sign-in-with-world-id/Redirects/RedirectInput/index.tsx
web/src/scenes/sign-in-with-world-id/Redirects/index.tsx
web/src/scenes/sign-in-with-world-id/Urls/UrlInput/index.tsx
web/src/scenes/sign-in-with-world-id/Urls/index.tsx
web/src/scenes/sign-in-with-world-id/index.tsx
web/src/stores/signInActionStore.ts
web/tests/integration/oidc/token.test.ts

- Fix conflicts with main
- Add tests for #383 
- Adjust token endpoint
- Used parsedParams instead of req.body where it's possible. (Please, review).

feat: PKCE token auth fix tests

---

web/src/scenes/actions/Action/index.tsx
web/src/scenes/actions/graphql/actions.generated.ts
web/src/scenes/actions/graphql/actions.graphql
web/src/scenes/actions/index.tsx

- added number of uses
- fixed horizontal scroll on page
https://github.com/worldcoin/developer-portal/assets/104859710/d1ef4c39-c61e-4358-8dec-2922bac89de3

feat: show number of uses in the nullifier

---

web/src/components/Layout/LoggedUserDisplay/index.tsx
web/src/scenes/signup/signup.tsx

1. Updates how user name displays
2. Fixes error when team name was not displayed right after signup

fix: logged user display

---

web/src/components/Layout/index.tsx
web/src/lib/urls.ts

fix: logout url

---

web/src/pages/api/v1/precheck/[app_id].ts

Adds new backwards compatible params following WDP24.

feat: add new params to precheck

---

web/pnpm-lock.yaml
web/src/pages/api/v1/oidc/authorize.ts

Closes [WID-602](https://linear.app/worldcoin/issue/WID-602/fix-oidc-nullifier-insertion-error-handling)
- Adds an additional check before inserting nullifier at /api/v1/oidc/authorize

feat: add additional check before insert nullifier

---

web/src/pages/app/sign-in.tsx

fixes a typo and updates sign in with worldcoin to sign in with world id

chore: update copy in Sign in with World ID page info

---

hasura/metadata/databases/default/tables/public_app.yaml
hasura/migrations/default/1704828243607_alter_table_app_verifications/down.sql
hasura/migrations/default/1704828243607_alter_table_app_verifications/up.sql

Hasura Changes to App Table to Accommodate App Verification. 
New Fields include: 
Category
Link to Integration
is_developer_allow_listing
is_reviewer_app_store_approved
is_reviewer_world_app_approved
world_app_description
approved_by

feat: Hasura Changes to App Table to Accommodate App Verification

---

web/src/components/Auth/Checkbox/index.tsx
web/src/components/FieldSelect/index.tsx
web/src/components/Layout/NewAppDialog/index.tsx
web/src/hooks/useApps.ts
web/src/lib/models.ts
web/src/scenes/actions/common/Form/FieldInput/index.tsx
web/src/scenes/actions/common/Form/FieldTextArea/index.tsx
web/src/scenes/app/AppHeader.tsx
web/src/scenes/app/Configuration.tsx
web/src/scenes/app/Form/FieldCheckbox.tsx

Add new fields to the UI and allow updating. This stuff currently publishes directly which replicates the unverified app flow. Next feature will be the verification flow. These values are not displayed anywhere currently so it shouldn't present any risks.

feat: app-database-form update with new fields

---

web/src/scenes/app/Configuration.tsx
web/src/scenes/app/Form/AppDescriptionSection.tsx
web/src/scenes/app/Form/AppLinksSection.tsx
web/src/scenes/app/Form/AppPublicationSection.tsx
web/src/scenes/signup/signup.tsx

Added source code and website url to the form. Refactor configuration form to extract the sections for better readability
This needs https://github.com/worldcoin/developer-portal/pull/446 to merge first

feat: Add new link fields to the form

---

hasura/metadata/databases/default/tables/public_action.yaml
hasura/metadata/databases/default/tables/public_api_key.yaml
hasura/metadata/databases/default/tables/public_app.yaml
hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/metadata/databases/default/tables/public_membership.yaml
hasura/metadata/databases/default/tables/public_nullifier.yaml
hasura/metadata/databases/default/tables/public_redirect.yaml
hasura/metadata/databases/default/tables/public_role.yaml
hasura/metadata/databases/default/tables/public_team.yaml
hasura/metadata/databases/default/tables/public_user.yaml

Noticed fixes while adjusting code for Hasura changes

fix: Hasura permissions

---

web/src/services/posthogClient.ts

Remove use server on post hog client to fix proofs not verifying

fix: proof fix

---

web/src/components/Layout/LoggedUserDisplay/TeamSelector/index.tsx
web/src/scenes/app/index.tsx

Closes [this](https://tfh.slack.com/archives/C05NJ4QFCLE/p1706041908769849?thread_ts=1706031364.968379&cid=C05NJ4QFCLE)
---
https://github.com/worldcoin/developer-portal/assets/89008845/1c6e7d1b-42f7-4930-b157-7919d31149a4

fix: team selector item url

---

web/src/scenes/team/team.tsx

fix: hide api section for members

---

web/src/scenes/team/Details/index.tsx
web/src/scenes/team/hooks/useTeam.ts

fix: show error on team member update

---

web/src/api/_invite-team-members/graphql/getMemberships.generated.ts
web/src/api/_invite-team-members/graphql/getMemberships.graphql
web/src/api/_invite-team-members/index.ts
web/src/scenes/team/MemberList/InviteMembersDialog/index.tsx

https://github.com/worldcoin/developer-portal/assets/89008845/60ef435a-1788-424a-9011-1b695f0082b8

fix: forbid to invite existing team members

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web-app-router/next-env.d.ts

Fix precheck not returning data if the user is not unverified or verified

Fix: Service permission

---

web-app-router/components/DecoratedButton/index.tsx

Still didn't succeed to make this border fade at the bottom, but this looks closer to design
Before: 
After:

refactor: button styles

---

web-app-router/components/Select/Button/index.tsx
web-app-router/components/Select/Option/index.tsx
web-app-router/components/Select/Options/index.tsx
web-app-router/components/Select/index.tsx
web-app-router/components/Selector/index.tsx
web-app-router/scenes/Portal/layout/TeamSelector/index.tsx
web-app-router/scenes/Portal/layout/index.tsx
web-app-router/tailwind.config.ts

- Added select component
Example of usage: https://github.com/worldcoin/developer-portal/blob/f81e5c2572116f899c9f46c37af993f31ba4ec58/web-app-router/components/Select/index.tsx

feat: select component

---

web-app-router/components/Tabs/Tab/index.tsx
web-app-router/components/Tabs/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx

feat: tabs component

---

web-app-router/next-env.d.ts
web/next.config.js
web/src/components/AppLogo/index.tsx
web/src/components/Layout/AppSelector/index.tsx
web/src/hooks/useImage/index.ts
web/src/lib/utils.ts
web/src/pages/api/v1/precheck/[app_id].ts
web/src/pages/team/[team_id]/kiosk/[action_id].tsx
web/src/scenes/app/AppHeader.tsx
web/tests/api/precheck.test.ts

Config needs to use virtual style urls to match staging and prod. Locally my bucket wasn't DNS compatible so it was displaying a different behavior. We also update the cloudfront urls to remove verified path since that's added into the origin url already.

Fix: Update next config

---

web-app-router/next-env.d.ts
web/src/hooks/useApps.ts

changed path to just check the pre file extension
the point of this check is to just make sure there's no URLs going in so we just check starts with will be sufficient. We enforce jpg and png on upload and on server.

fix: Bug fix jpg

---

web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/graphql/server/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/graphql/server/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/ProofDebuging/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/MaxVerificationsSelector/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx

Added team headers to graphql calls

Fix: Add team headers to graphql

---

web-app-router/scenes/Portal/Teams/TeamId/Team/Settings/page/graphql/client/update-team.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Team/Settings/page/graphql/client/update-team.graphql
web-app-router/scenes/Portal/Teams/TeamId/Team/Settings/page/index.tsx

feat: team settings page

---

web-app-router/lib/urls.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Common/ActionsHeader/graphql/client/get-action-name.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Common/ActionsHeader/graphql/client/get-action-name.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Common/ActionsHeader/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/graphql/client/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/graphql/client/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/ProofDebuging/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx

- Added Loading Skeleton
- Cleaned up Graphql
- Moved actions header to a common component to maintain liveness

WID 744: Actions page clean up 

---

web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/index.tsx

- cleaned up the graphql context and added skeleton loading
- also added an adjustment to the top bar so it doesn't completely brick when you reduce the screen size

Fix: Add Skeleton to Sign in and Cleanup

---

hasura/metadata/databases/default/functions/functions.yaml
hasura/metadata/databases/default/functions/public_action_stats.yaml
hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/metadata/databases/default/tables/public_nullifier.yaml
hasura/migrations/default/1707463125126_create_action_stats_table/up.sql
web-app-router/components/Chart/index.tsx
web-app-router/graphql/graphql.schema.json
web-app-router/graphql/graphql.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/graphql/client/update-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/graphql/client/update-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/StatCard/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/TimespanSelector/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/graphql/client/fetch-action-stats.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/graphql/client/fetch-action-stats.gql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/VerifiedTable/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/ActionsList/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx

- Update chart component to only show whole numbers (doesn't make sense to have decimals)
- Updated the Chart to show a point if there's no data 
- Added chart with aspect ratio to the graph
- Unfortunately the way we calculate verification is off but it's better imo to show # of verifications but the chart is messed up then not show the correct number of verification. We can revisit in the future how to fix this with better analytics 
- Adds Gradient to chart
Completes WID-731

WID-745 Actions page table frontend

---

web-app-router/scenes/Portal/layout/CreateAppDialog/index.tsx

fixed the copy at the top and removed image upload

Fix: update create app

---

hasura/migrations/default/1707493190197_alter_table_public_user_alter_column_team_id/down.sql
hasura/migrations/default/1707493190197_alter_table_public_user_alter_column_team_id/up.sql
web-app-router/scenes/Portal/Teams/TeamId/Team/Danger/page/DeleteTeamDialog/graphql/client/delete-team.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Team/Danger/page/DeleteTeamDialog/graphql/client/delete-team.graphql
web-app-router/scenes/Portal/Teams/TeamId/Team/Danger/page/DeleteTeamDialog/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Team/Danger/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Team/common/TeamProfile/graphql/client/fetch-team.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Team/common/TeamProfile/graphql/client/fetch-team.gql

- created a danger zone page
- added delete team modal

feat: danger zone logic

---

web-app-router/app/(unauthorized)/unauthorized/page.tsx
web-app-router/lib/utils.ts
web-app-router/middleware.ts
web-app-router/scenes/Portal/Profile/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/layout/graphql/server/fetch-app-env.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/layout/graphql/server/fetch-app-env.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/Links/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/Redirects/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/graphql/server/fetch-app-env.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/graphql/server/fetch-app-env.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Team/layout/index.tsx
web-app-router/scenes/Unauthorized/page.tsx

Created middleware route guards

Feat: WID-746 Route Guards

---

web-app-router/middleware.ts
web-app-router/styles/globals.css
web-app-router/tailwind.config.ts

Closes [WID-742](https://linear.app/worldcoin/issue/WID-742/[fix]-add-twk-lausanne-font)
- Adds TWK Lausanne font. 
@andy-t-wang Can you please double check the font URL?

feat: add twk lausanne font

---

web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/MiniKiosk/IDKitBridge/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/MiniKiosk/index.tsx

Kiosk dependency array was off before so it wasn't loading correctly. Also the kiosk wasn't reseting when actions changed

Fix kiosk reset and dependecy

---

web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/MiniKiosk/IDKitBridge/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/MiniKiosk/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/ActionsList/ActionRow/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/ActionsList/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.generated.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.graphql
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx
web-app-router/scenes/Root/providers/PostHogPageView.tsx

Fixed on chain actions cannot visit the kiosk or do max verification selector. Also blocked overview for on chain apps  
also added the $ back to pageview since that's the standard we use

[Fix] on chain cant do kiosk or max verifications

---

web-app-router/legacy/api/signup/index.ts
web-app-router/middleware.ts
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/ProofDebuging/Debugger/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/layout/index.tsx
web-app-router/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx
web/src/scenes/signup/signup.tsx
web/src/scenes/team/MemberList/InviteMembersDialog/index.tsx

- updated posthog to have a sign up success event with user id
- Reverted old changes accidentally updated in web folder not web-app-router
- added paths back to middleware

Fix middleware and posthog

---

web/styles/globals.css

Fix: fonts missing https

---

web/api/login-callback/index.ts

fix: replace req.url with env

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx

Delete for some reason needs the full query call just the document doesn't work it fails to find the query.
I removed the loading skeleton since it looks worse to have it load the page and then show the steps in my opinion. I'm not sure if there's a good way to do this without doing a seperate Graphql Query.

Fix action page remove flash delete await refetch

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/VersionSwitcher/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/layout/ImagesProvider/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/layout/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/common/ReviewStatus/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/index.tsx

- Fixed images to not pull on every page but instead through the layout via Image Provider. Moved the atoms into there
- Also update the links to specify we need https://
- Hide the verified button selector if the app is only verified

[Fix] Andywang images fix

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx

Add a null check to showcase images and center the empty image

[Fix] fixes the image errors Paolo mentioned

---

web/components/Dialog/index.tsx
web/components/InitialSteps/index.tsx
web/components/PlaceholderImage/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/page/ClientPage/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

- Removed skip tutorial
- Removed test it step (synced with lisa)
- Added a prefetch, it's slightly faster in some cases from what I've seen
- I ran into the dialog issue again but realize we need to make the base dialog component z-50. Tested it when I ran into the issue seemed to fix it

Fix: Clean up placeholder and fixes on steps

---

web/components/Checkbox/index.tsx
web/components/Input/index.tsx
web/components/TextArea/index.tsx
web/legacy/api/images/verify_app.ts
web/middleware.ts
web/package.json
web/pnpm-lock.yaml
web/scenes/Onboarding/CreateTeam/page/Form/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/ImageDisplay/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/RemainingCharacters/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/hook/use-image.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/AppStatus/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/common/hooks/use-remove-from-review.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/PermissionsDialog/index.tsx
web/scenes/Portal/layout/AppSelector/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

Many QOL Changes:
- Loading state for images
- Verify App allows for no image if user doesn't want an app store listing
- Check to prevent reviewers from verifying the app if there's no images
- Fixes to copy
- Disable the submit button if the user hasn't completed the required fields 
- Adds a warning if the page has been edited but not saved. 
- Fix toasts copy
- Make the entire DIV clickable for app store review checkbox
- Text area includes remaining character count
- Automatic Image compression as long as aspect ratio is correct. Relaxes the restriction on needing to upload exact dimensions. 
- Moved Remaining characters into a separate component to prevent the page from constantly re-rendering

[Fix] App Review + images feedback from Paolo

---

web/components/LoggedUserNav/TeamSwitch/index.tsx
web/components/LoggedUserNav/index.tsx
web/components/Radio/index.tsx
web/lib/urls.ts
web/scenes/Onboarding/CreateTeam/layout/index.tsx
web/scenes/Onboarding/CreateTeam/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/Settings/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Apps/App/AppLogo/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Apps/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/index.tsx
web/scenes/Portal/layout/AppSelector/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

Fix a bunch of connections on team. 
- Hide app selector on teams page since it looks weird where you need to suddenly choose an app.
- Added a create app button on the teams page so when you create a team you have something to click
- Toggle the apps based on teams 
- Fix Create Team Page Design
- Update App Page logic to handle switching teams, Currently it defaults to the first team stored in membership

[Fix] Permissions and Team QA changes

---

web/scenes/Root/page/graphql/server/fetch-memberships.generated.ts
web/scenes/Root/page/graphql/server/fetch-memberships.gql
web/scenes/Root/page/index.tsx

- Fixes redirects on a root page.

fix: redirects on root page

---

web/next.config.mjs

Fix logs by adding access control headers

[Fix] Add access control headers

---

web/next.config.mjs

Temp testing if buildtime vars are undefined. Will rollback

[Fix] Temp change to header

---

web/middleware.ts
web/scenes/Portal/Profile/Teams/page/List/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/ActionsList/DetailsMenu/index.tsx
web/services/posthogClient.ts

- server only 
- fix view details
- profile page title
- middleware font

[Fix] Fixes to details button posthog and middleware

---

web/api/create-team/graphql/insert-user.generated.ts
web/api/create-team/graphql/insert-user.graphql
web/api/create-team/index.ts
web/api/join-callback/graphql/insert-user.generated.ts
web/api/join-callback/graphql/insert-user.graphql
web/api/join-callback/index.ts
web/services/posthogClient.ts

We use a NEXT_PUBLIC variable because we have a posthog client side so the directive is breaking

[Fix] Add posthog id and fix directive

---

web/pages/api/v1/graphql.ts
web/scenes/common/me-query/client/graphql/client/me-query.generated.ts
web/scenes/common/me-query/client/graphql/client/me-query.gql

- Fixes posthog unique id error

fix: posthog id missing

---

hasura/metadata/databases/default/tables/public_membership.yaml

- added permission for leave team if not team owner

feat: leave team permission

---

web/components/Category/index.tsx
web/components/CodeBlock/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/CodeBlock/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

Added other since it could be blocking to have to pick a category. If we have tons of people putting other we can add more categories

Small changes from Feedback

---

web/api/login-callback/index.ts

- Fixes redirect after login-callback

fix: login callback redirect

---

web/scenes/Onboarding/CreateTeam/layout/CloseButton/index.tsx
web/scenes/Onboarding/CreateTeam/layout/index.tsx

fix: close create-team

---

hasura/metadata/databases/default/tables/public_invite.yaml
web/legacy/api/_invite-team-members/graphql/fetchInvites.generated.ts
web/legacy/api/_invite-team-members/graphql/fetchInvites.gql
web/legacy/api/_invite-team-members/graphql/updateInvitesExpiration.generated.ts
web/legacy/api/_invite-team-members/graphql/updateInvitesExpiration.gql
web/legacy/api/_invite-team-members/index.ts

- Fixes issue when invites are duplicated when you simply resend them
---
https://github.com/worldcoin/developer-portal/assets/89008845/0d794558-4e26-45c7-a8bd-0458bcdf28b9

fix: duplicated invites after resend

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/AppStatus/index.tsx
web/scenes/Portal/Teams/TeamId/Team/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/PermissionsDialog/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

[Fix] Clean up the copy

---

web/components/Icons/ChevronLeftIcon.tsx
web/components/Icons/ChevronRightIcon.tsx
web/components/Tabs/Tab/index.tsx
web/components/Tabs/index.tsx

feat: scrollable tabs for main navigation

---

web/components/Icons/LogoLines.tsx
web/components/InitialSteps/Step/index.tsx
web/components/InitialSteps/index.tsx
web/components/Radio/index.tsx
web/components/Tabs/Tab/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/ProofDebuging/Debugger/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/DeleteModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/RemainingCharacters/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/StatCard/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/page/ClientPage/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/index.tsx

Responsiveness was having issues with the relative divs
Fixed a change I accidentally made to check submit condition on button

[Fix] responsiveness and profile bug

---

web/package.json
web/pnpm-lock.yaml

https://nextjs.org/docs/messages/sharp-missing-in-production

[Fix] add sharp

---

web/api/login-callback/index.ts

This should fix 'Failed to find Server Action null' error
Suggestion: 
https://github.com/vercel/next.js/discussions/59105#discussioncomment-8573405

fix: replace NextResponse with Response

---

web/pages/api/v1/oidc/openid-configuration.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/ActionsHeader/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/index.tsx

Docs got updated so a bunch of the Urls are now broken

Fix docs links

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/Kiosk/Waiting/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/MaxVerificationsSelector/index.tsx

Make the test in simulator button pop when the user has copied the QR code
Update the action list so that it's more obvious it's scrollable

[fix] some small QOL stuff

---

web/pages/api/v1/verify/[app_id].ts

We want to track if people are orb or device verifying

Add credential type to verify event

---

web/pages/api/v1/verify/[app_id].ts

Action verify was missing a capture event

[Fix] Fix missing capture event

---

web/api/update-session/index.ts
web/tests/unit/update-session.test.ts

Clean-up some small checks around updating user

[Fix] Clean up user

---

web/components/Dialog/index.tsx
web/components/DialogOverlay/index.tsx
web/components/DialogPanel/index.tsx
web/scenes/Portal/Profile/DangerZone/DeleteAccountDialog/index.tsx
web/scenes/Portal/Profile/Teams/page/LeaveTeamDialog/index.tsx
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/TimespanSelector/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/ActionStatsGraph/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/DeleteModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/TimespanSelector/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/common/ReviewMessageDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ApiKeyRow/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/DeleteKeyModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ViewDetailsModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/CreateKeyModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/InviteTeamMemberDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/EditRoleDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/PermissionsDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/RemoveUserDialog/index.tsx
web/scenes/Portal/common/DeleteTeamDialog/index.tsx
web/tailwind.config.ts

- refactored modal
- added mobile variant
- added animation for desktop and mobile variants

refactor: mobile modals

---

web/api/public/app/[app_id]/index.ts
web/api/public/apps/index.ts
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

Img urls missing the cdn url and the limit default.

[Fix] IMG urls

---

web/components/Icons/CollapseIcon.tsx
web/components/Icons/ExpandIcon.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/EditRoleDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/PermissionsDialog/index.tsx
web/tailwind.config.ts

feat: mobile team permissions dialog

---

web/scenes/Portal/Profile/Teams/page/List/index.tsx

refactor: user profile team dropdown on mobile

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/VersionSwitcher/index.tsx

refactor: app version dropdown on mobile

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/ActiveKiosk/index.tsx

refactor: kiosk dropdown on mobile

---

web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ApiKeyRow/index.tsx

refactor: api key list dropdown on mobile

---

web/scenes/Portal/Teams/TeamId/Team/page/Members/List/index.tsx

refactor: team member dropdown on mobile

---

web/api/public/app/[app_id]/index.ts
web/api/public/apps/index.ts
web/lib/utils.ts
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

[fix] caching public apis

---

web/components/Icons/MinusIcon.tsx
web/components/Icons/PlusIcon.tsx
web/scenes/Portal/Profile/Teams/page/List/TeamLogo/index.tsx
web/scenes/Portal/Profile/Teams/page/List/index.tsx
web/scenes/Portal/Profile/Teams/page/index.tsx
web/scenes/Portal/Profile/common/UserInfo/index.tsx
web/scenes/Portal/Profile/layout/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/CodeBlock/CodeDisplays/index.tsx

refactor: profile teams screen on mobile

---

web/components/Table/Body/index.tsx
web/components/Table/Footer/index.tsx
web/components/Table/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ApiKeyRow/Status/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ApiKeyRow/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/common/TeamProfile/index.tsx

refactor: team api keys on mobile

---

web/scenes/Portal/Teams/TeamId/Team/page/Members/List/EditRoleDialog/index.tsx

refactor: member role select on mobile

---

web/app/(portal)/teams/[teamId]/(team)/app/page.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/index.tsx
web/scenes/Portal/Teams/TeamId/Team/Apps/page/index.tsx
web/scenes/Portal/Teams/TeamId/Team/layout/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/EditRoleDialog/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/index.tsx

refactor: team members on mobile

---

web/next.config.mjs

Then we need to submit it here https://hstspreload.org/?domain=developer.worldcoin.org.
Based on what I see online we should set it to over a year. Examples I see suggest 2 years (63072000 seconds)

[Fix] HSTS Header

---

hasura/metadata/databases/default/tables/public_app_rankings.yaml

[Fix] add insert permissions to app rankings

---

web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/public/app/[app_id]/index.ts
web/api/public/apps/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-metadata.graphql
web/api/public/apps/graphql/get-app-rankings.generated.ts
web/api/public/apps/graphql/get-app-rankings.graphql
web/api/public/apps/index.ts
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

- Add description
- add team name
- Add return default if country doesn’t exist.

[Fix] api endpoints

---

web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/public/app/[app_id]/index.ts
web/api/public/apps/index.ts
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

Return the same values for web
note description is now 
```
"description": {
"overview": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_overview",
"how_it_works": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_how_it_works",
"how_to_connect": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_connect"
},
```
instead of
```
"description": {
"description_overview": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_overview",
"description_how_it_works": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_how_it_works",
"description_how_to_connect": "world_id_partner_app_175429b645169ac1a9e25dc9c962663e_connect"
},
```

localise web

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web/legacy/api/images/verify_app.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx

App store permissions were incorrect leading to verify not working and create new draft to be broken
Updated the error checking in verify to actually check a row was verified

[Fix] permissions for app store

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1713898610628_alter_table_public_app_metadata_miniapps/down.sql
hasura/migrations/default/1713898610628_alter_table_public_app_metadata_miniapps/up.sql
web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/public/apps/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-metadata.graphql
web/api/public/apps/index.ts
web/app/(portal)/teams/[teamId]/apps/[appId]/profile/mini-app/page.tsx
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/graphql/client/update-mini-app.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/graphql/client/update-mini-app.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/layout/index.tsx
web/tests/api/public/app.test.ts
web/tests/api/public/apps.test.ts

Adds a new section for apps to specify information to miniapps
Updates endpoints to return app_mode and whitelisted_addresses. Also lets you query apps of only a certain type via a new app_mode query param
Note the addresses section is not end state, just temp state until we have design update it. 
completes wid-926

App Directory (Mini apps)

---

web/scenes/Portal/Teams/TeamId/Team/page/Apps/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx

- restored create app button logic
- fixed create app dialog closing on mobile

fix: create app button

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx

- blocked links in app descriptions

feat: block links in app descriptions

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx

fix: create action dialog closing on mobile

---

.github/workflows/ci-app-router.yml
web/Dockerfile
web/next.config.mjs
web/package.json
web/pnpm-lock.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.graphql

Update to the app metadata query broke the delete process. Updating here to fix it
- Updated the docker image to be more efficient as part of dev portal migration
- Updated nextjs version to handle the server action null issue as well as dd logs which will create request issues later
completes WID-881

Update Docker, upgrade nextjs, fix a delete bug

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/DeleteModal/index.tsx

Fix App Deletion Bug in linear

fix App Deletion bug

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

Var names got changed in backend update, updating here as well

fix var names

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

Internal api is returning a 403. Probably a API gateway issue but want to print logs

[Fix] print logs

---

web/pages/api/v1/oidc/authorize.ts

Capture sign in events for KPI

Feat: Capture Sign In

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Transaction endpoint is not logging the errors

Fix: Add log to transaction endpoint

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/package.json
web/pnpm-lock.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts
web/tests/api/v2/minikit-transaction.test.ts

Dev portal connection to backend requires a signed fetch. Converting the fetch to this

Fix: Signed Fetch

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Cannot see logs right now when the internal call fails

fix: Fix Logs

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/legacy/api/images/get_unverified_images.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

The region was incorrect so the request was failing.

Fix: Incorrect Region

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/TransactionsTable/TransactionRow/Token/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/TransactionsTable/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

Transaction connection and data pulling is now working fine

Fix: Clean up, working transaction connection and data pulling now

---

web/lib/types.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/TransactionsTable/TransactionRow/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

reference id was changed to reference in the backend endpoint.

Fix: Update reference field

---

hasura/metadata/databases/default/tables/public_action.yaml
web/api/v2/create-action/graphql/create-dynamic-action.generated.ts
web/api/v2/create-action/graphql/create-dynamic-action.gql
web/api/v2/create-action/index.ts

Create actions endpoint was failing previously because of strict and lacking permissions.

Fix: Create actions endpoint

---

web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/app/[app_id]/graphql/get-app-metadata.graphql

App endpoint should allow pulling non app store approved apps to support universal links flow. 
https://www.notion.so/worldcoin/Mini-Kit-Universal-Links-42e3663b78dc46f5ba30a8c4181ebc36?pvs=4

Remove App store restriction

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/fetch-api-key.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/fetch-api-key.gql
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/app/api/v2/minikit/app-metadata/[app_id]/route.ts
web/tests/api/v2/minikit-app-metadata.test.ts

Create endpoint to let users query app-metadata if the api key is defined and it matches the app

feat: Developer mode endpoint

---

web/legacy/backend/errors.ts
web/package.json
web/pages/api/v1/debugger.ts
web/pages/api/v1/graphql.ts
web/pages/api/v1/oidc/authorize.ts
web/pnpm-lock.yaml

We are getting a bunch of failed to parse formdata errors with playwright
https://github.com/microsoft/playwright/issues/30788. Based onwhat I see here there seems to be an error introduced in 1.44 with parsing form data. Perhaps this will fix it

Improve Logging

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx

Synced with designs going forward we want the aspect ratio of the images to be 1:1

Feat: Change Aspect Ratio

---

web/pages/api/v1/oidc/authorize.ts
web/scenes/Portal/Profile/DangerZone/DeleteAccountDialog/index.tsx
web/scenes/Portal/Profile/Teams/page/LeaveTeamDialog/index.tsx
web/scenes/Portal/Profile/Teams/page/TransferTeamDialog/index.tsx
web/scenes/Portal/Profile/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Danger/ActionDangerZoneContent/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Danger/page/DeleteModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Error/error.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Links/page/LinksForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/StoreInfo/page/UpdateStoreInfoForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/hook/use-image.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/error/error.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/Links/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/Redirects/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/DeleteKeyModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/ApiKeyTable/ViewDetailsModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/ApiKeys/page/CreateKeyModal/index.tsx
web/scenes/Portal/Teams/TeamId/Team/Settings/page/index.tsx
web/scenes/Portal/common/DeleteTeamDialog/index.tsx

Improves sign in logs to reduce on call triggers
Still not able to figure out the Failed to parse body as FormData.

Fix: Improve Logs

---

web/components/DialogPanel/index.tsx
web/scenes/Portal/layout/CreateAppDialog/index.tsx
web/scenes/Portal/layout/Header/index.tsx

Currently the create app modal doesn't work on mobile. It's not scrolling

Fix: Modal UI

---

web/lib/utils.ts

Missing user count, waiting on metrics service but adding to unblock

Fix: Add user count

---

docker-compose-test.yaml
docker-compose.yaml
web/api/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-metadata.generated.ts
web/api/public/apps/graphql/get-app-rankings.generated.ts
web/api/public/apps/index.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-web-highlights.generated.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/legacy/api/images/get_app_review_images.ts
web/legacy/api/images/get_unverified_images.ts
web/legacy/api/images/graphql/getAppMetadata.generated.ts
web/legacy/api/images/graphql/getAppReviewImages.generated.ts
web/legacy/api/images/graphql/getUnverifiedImages.generated.ts
web/legacy/api/images/verify_app.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/graphql/client/update-showcase-image.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/graphql/client/update-showcase-image.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Gallery/page/ImageForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/graphql/client/update-mini-app.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/graphql/client/update-mini-app.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/graphql/client/create-editable-row.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts

- Updates hasura image version
- Updates types

Upgrade Hasura version and fix types

---

web/api/v2/public/apps/index.ts
web/lib/types.ts

Update native app, app_ids to be static across environments

Fixed Native App Ids

---

web/api/v2/public/apps/index.ts

Fix v2 endpoint images. We set the app_id to a different value so it was breaking the setting of the CDN url.

Fix images

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/tests/api/v2/minikit-app-metadata.test.ts

Add missing fields to test metadata endpoint

Update test metadata endpoint

---

web/Dockerfile

Docker file wasn't fixed version, next logger released a new version and it created a race condition where the package pino wasn't installed

Fix docker file

---

web/.env.test
web/Dockerfile
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/types.ts
web/lib/utils.ts
web/package.json
web/pnpm-lock.yaml
web/tests/api/v2/public/apps/apps-metadata.test.ts

Adding stats pulled from the metrics service

Feat: Add App Stats

---

web/api/helpers/jwks/index.ts
web/api/helpers/jwts.ts
web/api/helpers/kms.ts
web/legacy/backend/jwks.ts
web/legacy/backend/jwts.ts
web/legacy/backend/kms.ts
web/tests/api/__mocks__/kms.mock.ts
web/tests/api/oidc/authorize.test.ts
web/tests/integration/oidc/token.test.ts

Reverts worldcoin/developer-portal#792

Revert "feat: switch from RS256 to PS256 for OIDC JWT"

---

web/api/public/apps/index.ts
web/tests/api/public/apps.test.ts

Making a temp change so V1 enforces only showing external apps. This is because will publish some mini apps on prod and we don't want them to be shown. It's too late to add a feature flag now

temp v1 change

---

web/lib/constants.ts

Add native apps for production

Add native apps for prod

---

hasura/metadata/api_limits.yaml

Add batch limits

---

web/api/v2/public/apps/index.ts

Added cloud front header for country code. Checking this

Test cloudfront header

---

web/api/v2/public/apps/index.ts

log country

---

web/api/v2/public/apps/index.ts

Remove country log and lowercase since we are using  ISO 3166-1 alpha-2 so they will all be capitalized

Remove country log

---

web/api/v2/public/apps/index.ts
web/lib/types.ts
web/lib/utils.ts

Implement sorting of apps based on 7 days unique views

Feat: Sort on views

---

web/api/login-callback/index.ts

Previous the redirect was failing without the entire URL was leading to 500 error

Fix redirect issue on join team

---

web/api/login-callback/index.ts
web/middleware.ts

Checking if our logging issues are rooted in middleware.

Catch middleware issues

---

web/api/login-callback/index.ts
web/components/Unauthorized/index.tsx
web/lib/urls.ts
web/scenes/Unauthorized/page.tsx

Improve Error Messages

---

hasura/metadata/databases/default/tables/public_action.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/ActiveKiosk/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/index.tsx
web/scenes/Portal/Teams/TeamId/Team/page/Members/List/PermissionsDialog/index.tsx

Creates a new link for Kiosk to use the general Kiosk Page.
Also changes permissions such that members can create new actions but cannot edit existing actions. Potentially we just remove their ability to create actions or create a viewer role for the kiosk

Kiosk Improvements

---

web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/lib/utils.ts
web/tests/api/v2/minikit-app-metadata.test.ts

fix-test mode

---

docker-compose.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/MiniApp/page/MiniAppForm/index.tsx

Enables countries for all apps

Enable countries for all apps

---

web/lib/constants.ts

Temporary app for IOS in staging

Temp Native App in IOS

---

web/components/Input/index.tsx
web/components/SelectMultiple/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx

Setup Page needed to be improved. We want to require these fields for all apps now. Additionally require english
https://github.com/worldcoin/developer-portal/assets/41224501/b76a00d6-c355-4d69-82e7-b381d8eeb925

Improve setup branch

---

hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/metadata/databases/default/tables/public_localisations.yaml
web/components/CountryBadge/index.tsx
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/fetch-localisation.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/fetch-localisation.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/insert-localisation.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/insert-localisation.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/update-localisation.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/graphql/client/update-localisation.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/index.tsx

Will create one more PR for creating a new draft. This will involve creating a hasura custom action
https://github.com/user-attachments/assets/4d9f78c9-5dbd-4778-b07b-a4cb0a3e7685

Create localisation UI

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/index.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/lib/types.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps-metadata.test.ts

Add locale pulling and default to english if the locale is not specified

Update directory with locales

---

web/lib/urls.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx

- fixes initial render not working for lazy query
- adds anchor

Localisation bug fix

---

web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/lib/constants.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/helpers/form-countries-list.ts

Localise categories

---

web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql

Highlights needed some additional query params

add highlights query params

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/PageComponents/AppTopBar/index.tsx

Staging apps should not be able to submit for review

Remove staging app submit

---

web/pages/api/v1/oidc/authorize.ts

Add a check to make sure password isn't undefined

fix detection of env

---

web/pages/api/v1/oidc/authorize.ts

remove stray console log

---

web/lib/categories.ts
web/lib/constants.ts
web/package.json
web/pnpm-lock.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx

This handles situations where invalid locales are passed to the directory endpoint

Handles invalid locales being passed

---

web/api/v2/app/submit-app-review/index.ts

Native apps have their app_ids changes so their external nullifier was incorrect

Native app support for app reviews

---

web/api/v2/app/submit-app-review/index.ts

Fix in operator

---

web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/languages.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx

Parse Localisation

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Improve error messages for transaction endpoitn

Improve transaction error message

---

web/api/v2/public/apps/index.ts

logging locale to debug incoming requests from app directory

Log locale

---

web/api/v2/public/apps/index.ts

Retry logs

---

web/api/v2/public/apps/index.ts

Use Incoming Header

---

.github/workflows/ci-app-router.yml
web/api/v2/public/apps/index.ts
web/lib/utils.ts
web/tests/api/v2/minikit-app-metadata.test.ts

Improve defaults in short name such that we use the name if short name is undefined

Improve defaults in endpoint

---

hasura/migrations/default/1723063311225_allow_local_host_for_development/down.sql
hasura/migrations/default/1723063311225_allow_local_host_for_development/up.sql
web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx

Allow local host testing

---

web/api/v2/public/apps/index.ts

Fix native users unique human count. Need to swap in app id to get correct count for native users

Fix native users unique human count

---

hasura/migrations/default/1723148219538_revert_local_host_changes_to_urls/down.sql
hasura/migrations/default/1723148219538_revert_local_host_changes_to_urls/up.sql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/page/BasicInformation/index.tsx

We will recommend developers to use NGROK instead since we dont' want to remove our firewall protections for ip addresses in request body

Revert Link Changes

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

test transaction error

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Test logging for the endpoint failing in production

Test Logging

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

improve logging errors

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

We are adding headers for transactions since right now we get firewall errors

Add headers for transactions

---

web/api/v2/public/apps/index.ts

Fix User Count

---

web/lib/types.ts
web/lib/utils.ts
web/tests/api/v2/minikit-app-metadata.test.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps-metadata.test.ts

Add associated domain. Placeholder until I implement front end to unblock

Add associated domains

---

web/scenes/Onboarding/Login/page/index.tsx

revert fix

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1725278962961_add_crypto_permissions/down.sql
hasura/migrations/default/1725278962961_add_crypto_permissions/up.sql
web/api/hasura/create-new-draft/graphql/fetch-metadata.generated.ts
web/api/hasura/create-new-draft/graphql/fetch-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/components/TextArea/index.tsx
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql

Add new fields
Contracts and permit2 tokens to be in the permissions.

Add smart contract values

---

web/api/hasura/create-new-draft/graphql/create-draft.generated.ts
web/api/hasura/create-new-draft/graphql/create-draft.graphql
web/api/hasura/create-new-draft/index.ts

Should figure out a way to unify the queries since all of these require manual updates each time and it's a bit of a hassle to remember each one. Create new draft was missing types

Fix Create New Draft

---

web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql

Fix Metadata Endpoint

---

web/components/TextArea/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx

Adding an onchange was overriding the yup on change call

Fix Validation for text areas

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1726177042301_add import all contacts/down.sql
hasura/migrations/default/1726177042301_add import all contacts/up.sql
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql

Add an option to import all contacts. Soon I will refactor this so I dont need to modify 10 graphql queries each time I add a new field

Add import all contacts option

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1726177042301_add import all contacts/down.sql
hasura/migrations/default/1726177042301_add import all contacts/up.sql
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql

Reverts worldcoin/developer-portal#921

Revert "Add import all contacts option"

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/lib/types.ts
web/lib/utils.ts

Updates the app store to accomodate the open app store structure

Open app store

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1726177042301_add import all contacts/down.sql
hasura/migrations/default/1726177042301_add import all contacts/up.sql
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/pages/api/v1/oidc/validate.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/graphql/client/update-setup.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/graphql/client/fetch-app-metadata.graphql

Add back Allow All Contacts

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web/lib/types.ts

Add missing types in the return value

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts

Directory is already cached no need to cache the stats

No cache on stats

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/lib/types.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/TransactionsTable/TransactionRow/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/TransactionsTable/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

add transaction hash fetching endpoint

Add transaction hash fetching endpoint

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/package.json
web/pnpm-lock.yaml

https://github.com/vercel/next.js/security/advisories/GHSA-gp8f-8m3g-qvj9

Upgrade Next

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/next-env.d.ts

We need to always fetch unverified metadata for the test mini app /api

Unverified Metadata

---

web/api/hasura/invalidate-cache/index.ts

Fix: Fix Cache

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/lib/types.ts
web/lib/utils.ts

V2 endpoint was not working cause I was using the wrong field. App store not world app. We don't care about app store right now.

Fix V2 Endpoint

---

web/api/v2/minikit/send-notification/index.ts
web/api/v2/public/apps/index.ts

Fix error handling and spelling

Fix error handling and spelling

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

Fix hasura permissions for retool

fix permissions

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Profile/Setup/page/SetupForm/index.tsx

closes DEV-1124
@andy-t-wang needs clarification on scope
edit: after clarification, only the typo will be updated

DEV-1124 fix typo and link validation

---

web/scenes/Portal/layout/CreateAppDialog/graphql/client/insert-app.generated.ts
web/scenes/Portal/layout/CreateAppDialog/graphql/client/insert-app.gql
web/scenes/Portal/layout/CreateAppDialog/index.tsx
web/tests/e2e/specs/app.spec.ts

Dev Portal UI Refactor: Entry Point Update

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/layout/index.tsx

Routes were wrong rip

---

web/scenes/Portal/layout/CreateAppDialog/index.tsx

fix default values for create app

Fix default values for create app

---

hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/default/tables/public_notification_log.yaml
hasura/metadata/databases/default/tables/public_notification_log_wallet_address.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/graphql/client/actions.graphql

Validate localisation changed to a mutation object but the hasura update didn't propogate

Fix submit app

---

web/api/v2/minikit/send-notification/graphql/create-notification-log.graphql

remove anxiety inducing comment

remove comment

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/tests/api/v2/minikit-transaction.test.ts

Cors and open API

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Handle Cors

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/app/api/v2/minikit/transaction/[transaction_id]/route.ts

Need to add options endpoint for cors 
https://github.com/vercel/next.js/discussions/47933

Options Cors Issues

---

hasura/metadata/databases/default/tables/public_localisations.yaml

Allows the reviewer role to see localise

Allow reviewer to see localise

---

web/lib/utils.ts

provide a correct url for unverified images

DEV-1145 url for unverified app images

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

Fix Metadata

---

hasura/migrations/default/1728039537362_app_is_banned_non_null/down.sql
hasura/migrations/default/1728039537362_app_is_banned_non_null/up.sql

Is banned has two falsy types now null and false. We should default to false

fix migration

---

hasura/metadata/databases/databases.yaml

Bumped db reduce total connections allowed to 30

reduce total connections

---

web/lib/constants.ts

fix invites

---

web/pages/api/v1/oidc/authorize.ts

improve errors sign in

---

web/api/v2/app/submit-app-review/index.ts

count app review as it uses world id too

count app review

---

web/pages/api/v1/oidc/authorize.ts

Fix Has Error

---

web/api/v2/public/apps/index.ts

no cache metrics

---

web/lib/constants.ts

revert invites. For some reason someone made a TFH invites and it resulted in duplicate so I removed it. we should not be having two

Revert invites

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/QuickActionsSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/VerificationStatusSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-verification-data.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-verification-data.gql
web/scenes/Portal/Teams/TeamId/Apps/common/ReviewMessageDialog/index.tsx
web/scenes/Root/providers/providers.tsx

fix review message for dev portal

fix review message

---

web/api/v2/minikit/send-notification/index.ts
web/lib/logger.ts

Logging improvements: Notifications. Additionally this will improve our error logging

Logging Improvements: Notifications

---

web/api/helpers/verify.ts
web/legacy/backend/verify.ts
web/package.json
web/pnpm-lock.yaml
web/tests/e2e/specs/app.spec.ts

upgrade ethers

---

web/api/helpers/jwts.ts
web/api/helpers/kms.ts

fix sign in types. requires uint8 array not buffer

fix sign in types

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/QrQuickAction/index.tsx

fix universal link. link is worldcoin.org not world.org. Thanks @karankurbur

fix universal link

---

web/api/v2/public/app/[app_id]/index.ts
web/scenes/Portal/Teams/TeamId/Apps/common/ReviewMessageDialog/index.tsx

incorrect metrics service endpoint and need to add an anti loading state for 404

Fix weird styling and issue with unique_users count

---

web/api/public/app/[app_id]/index.ts
web/lib/constants.ts
web/lib/utils.ts

Create whitlelist ability for permit2 tokens

Whitelist permit2 tokens

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/legacy/lib/logger.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/getAccumulativeTransactionData.ts

Rename try it out url. Moving more to logger since we should standardize logging in dev portal right now it's very messy

Rename Try it Out URL

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/Kiosk/IDKitBridge/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/ActiveKiosk/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/page/ImageForm/ImageLoader/index.tsx

Improve polling

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/Kiosk/IDKitBridge/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Kiosk/ActiveKiosk/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/page/ImageForm/ImageLoader/index.tsx

Reverts worldcoin/developer-portal#1013

Revert "Improve polling"

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/constants.ts
web/lib/types.ts

hardcode world chat

---

web/lib/constants.ts

Fix world chat url

---

web/Dockerfile
web/package.json
web/pnpm-lock.yaml

Attempting to fix memory leak issue: https://github.com/vercel/next.js/discussions/68636

Fix Node Version

---

web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/index.ts

Update query conditions

---

web/pages/api/v1/oidc/authorize.ts

Handle Edge Case catching with redis

Redis Error Catching

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/index.tsx

update the logo

---

web/lib/constants.ts

Remove worldchat native denotation

Remove Worldchat Native denotation

---

hasura/metadata/databases/databases.yaml

reduce number of active sessions

Reduce number of active sessions

---

hasura/metadata/databases/databases.yaml

reduce connection time

---

cspell.json
hasura/migrations/default/1731362032660_optimize_indexes/down.sql
hasura/migrations/default/1731362032660_optimize_indexes/up.sql
web/tests/api/v2/public/apps/apps-metadata.test.ts

Split and fix tests

---

cspell.json
hasura/migrations/default/1731362032660_optimize_indexes/down.sql
hasura/migrations/default/1731362032660_optimize_indexes/up.sql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/api/v2/public/apps/index.ts
web/tests/api/v2/public/apps/apps-metadata.test.ts

split queries

---

hasura/metadata/databases/databases.yaml
hasura/migrations/default/1731366080224_create_index_action_id_uses/down.sql
hasura/migrations/default/1731366080224_create_index_action_id_uses/up.sql

Add nullifier uses index

---

hasura/migrations/default/1731362032660_optimize_indexes/up.sql
hasura/migrations/default/1731385475816_remove_unique_index/down.sql
hasura/migrations/default/1731385475816_remove_unique_index/up.sql

Index cannot be unique 
https://app.datadoghq.com/logs?query=env%3Aproduction%20service%3Aworldcoin-developer-portal&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZMem0xXpLfI9wAAABhBWk1lbTAyMEFBRDVDak44MmNmRkZ3QW8AAAAkMDE5MzFlOWItOTYzMi00MTcwLTgyYmEtYzlkMmFlMTJkMGMwAAWO6g&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1717517944341&to_ts=1717518844341&live=true

Index not unique

---

web/api/v2/verify/index.ts

See why we have an issue inserting nullifiers

improve verify logs

---

web/api/v2/verify/index.ts

Improve verify error message

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/FormSubmitStateProvider/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/PageComponents/AppTopBar/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/PageComponents/AppTopBar/index.tsx
web/scenes/Portal/Teams/TeamId/Team/layout/index.tsx

After submitting on `App Store` tab, we show an error if there isn't a logo image

Copy and error msg fixes

---

web/lib/frontend-api.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/CodeBlock/index.tsx

Use v2 of API

---

web/api/helpers/app-store.ts
web/lib/utils.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/hook/use-image.tsx

Handle Errors

---

web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/pages/api/v1/precheck/[app_id].ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/VerifiedTable/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/page/graphql/client/get-single-action.graphql

Nullifiers table is pulling too many rows

Improve nullifiers table

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/getAccumulativeTransactionData.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/index.ts

ci fails bc of disabled ratings, previously existing change

log transaction table/chart errors always

---

hasura/metadata/databases/default/tables/public_app_report.yaml
hasura/migrations/default/1732626626712_app_report_purpose_violation_columns/down.sql
hasura/migrations/default/1732626626712_app_report_purpose_violation_columns/up.sql

add purpose&violation columns to app_report

---

web/@types/global.d.ts
web/api/helpers/app-rating/index.ts
web/instrumentation.ts
web/jest.setup.ts
web/next.config.mjs
web/pages/api/v1/oidc/authorize.ts
web/tests/api/oidc/authorize.test.ts
web/tests/integration/oidc/authorize.test.ts

Should not close redis connection

Fix instrumentation file with redis

---

web/lib/constants.ts

Add factory to permit2 whitelist

add factory to whitelist

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/PageComponents/AppTopBar/LogoImageUpload/index.tsx

change logo copy to show 500kb instead of 250kb

change logo copy

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/PageComponents/AppTopBar/LogoImageUpload/index.tsx

logo error:
also fixed some values resetting on save & inability to select a country on a new app

logo error & form logic fix

---

hasura/metadata/databases/default/tables/public_app.yaml
hasura/migrations/default/1733533994467_compute_ratings/down.sql
hasura/migrations/default/1733533994467_compute_ratings/up.sql
web/api/v2/app/submit-app-review/graphql/fetch-current-app-review.generated.ts
web/api/v2/app/submit-app-review/graphql/fetch-current-app-review.graphql
web/api/v2/app/submit-app-review/graphql/update-review-counter.generated.ts
web/api/v2/app/submit-app-review/graphql/update-review-counter.graphql
web/api/v2/app/submit-app-review/index.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/tests/api/v2/app/submit-app-review.test.ts

Creates a new column in the app table that precomputes the ratings for the app. PT2 will be actually pulling this value in the app metadata endpoint

Fix App Ratings

---

web/api/helpers/app-store.ts

Add default rating

---

web/api/helpers/app-store.ts

default update

---

hasura/metadata/actions.yaml
web/graphql/graphql.schema.json
web/graphql/graphql.ts

action was set to async by mistake, regenerated schema and gql types

fix: async action to sync, regen gql types

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/BanStatusSection/ban-status.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/BanStatusSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-is-app-banned.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-is-app-banned.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/common/BanMessageDialog/index.tsx

Plan later is to change the text to point devs to the email (once we actually start sending them)

feat: app ban alert

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/BanStatusSection/index.tsx

fix: correct app ban status logic

---

hasura/migrations/default/1734649515450_alter_table_public_action_add_unique_external_nullifier/down.sql
hasura/migrations/default/1734649515450_alter_table_public_action_add_unique_external_nullifier/up.sql

Remove constraint. Will add this back later

Remove Constraint

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

Add changelog permissions

---

web/api/helpers/app-store.ts
web/lib/constants.ts

Whitelist Uno

---

hasura/migrations/default/1734715059615_enforce-whitelist/down.sql
hasura/migrations/default/1734715059615_enforce-whitelist/up.sql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/QrQuickAction/index.tsx

Validation of addresses related to #1106

Validation of addresses

---

web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/lib/types.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts
web/tests/integration/auth/join-callback.test.ts
web/tests/integration/auth/login-callback.test.ts

Expose notification metadata

---

web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/tests/api/v2/public/apps/apps.test.ts

temp fix ios links

---

web/lib/languages.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

some minor refactoring, added a description spread so that it gets updated on locale change

Fix localisation form

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBar/SubmitAppModal/index.tsx

metadata gets refetched on app submit

fix: refetch metadata on app submit

---

web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/tests/api/v2/public/apps/apps.test.ts

Reverts worldcoin/developer-portal#1109. Wasn't the cause of the IOS issues

Revert "temp fix ios links"

---

web/api/helpers/app-store.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/minikit/app-metadata/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/minikit/send-notification/index.ts
web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/lib/types.ts
web/scenes/Portal/Profile/page/index.tsx
web/tests/api/v2/minikit-app-metadata.test.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

Temporarily fixing notifications in order to not break since we don't have the fields yet to let developers request this permission

Temp notifications fix

---

web/api/v2/minikit/send-notification/index.ts
web/tests/api/v2/send-notification.test.ts

Validation to notification endpoint. 
Enforce max addresses
Max Payload Size
Require Wallet Addresses
Add tests

Improvements to notification endpoint

---

web/api/helpers/errors.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/server/submit.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/server/submit.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBar/server/submit.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/server/submit.ts
web/scenes/Portal/layout/CreateAppDialog/server/submit.ts

fix: prevent excessive error logs

---

web/api/v2/minikit/send-notification/index.ts

remove unused params from backend endpoint

Remove unused params

---

web/api/hasura/create-new-draft/graphql/create-draft.generated.ts
web/api/hasura/create-new-draft/graphql/create-draft.graphql
web/api/hasura/create-new-draft/graphql/fetch-metadata.generated.ts
web/api/hasura/create-new-draft/graphql/fetch-metadata.graphql
web/api/hasura/create-new-draft/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/graphql/server/update-setup.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/graphql/server/update-setup.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/server/submit.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/graphql/client/fetch-app-metadata.graphql

sucessfuly copies on new draft creation

Notifications and contacts

---

.github/dependabot.yml
.github/pull_request_template.md

Add template requirement for dev portal

Add template requirement

---

web/api/v2/minikit/send-notification/index.ts

Temporarily see the notifications

temp see notifications

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Improve error logging on this endpoint so we know what is causing the transaction fetching to fail

restructure errors

---

web/api/helpers/app-store.ts
web/api/v2/minikit/send-notification/graphql/fetch-metadata.generated.ts
web/api/v2/minikit/send-notification/graphql/fetch-metadata.graphql
web/api/v2/minikit/send-notification/index.ts
web/tests/api/v2/minikit-app-metadata.test.ts
web/tests/api/v2/send-notification.test.ts

Notifications has the form to request now in dev portal so removing this restriction and hack

Remove notification restriction

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/tests/api/v2/minikit-transaction.test.ts

People are requesting this with crazy graphql things we are adding schema validation in here.

Add schema validation to send transaction

---

web/lib/schema/index.ts

after testing with some more sample texts in diferent languages, i included more common and harmless characters

fix: add more special characters to long form text regex

---

web/lib/categories.ts

This PR adds 4 new app categories:
- Token
- External
- Earn 
- AI

Add new app categories

---

web/lib/languages.ts

This PR adds support for Malay language. Clients can query /apps endpoint with `x-accept-language: ms-MY or ms` to get localised responses.

Add support for malay language

---

web/lib/categories.ts

Add malay category translations

Add malay category translations

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

Give reviewer the ability to change app categories

review gets category permissions

---

web/lib/constants.ts

Whitelist the DNA app for permit2

Whitelist dna

---

web/lib/constants.ts

Whitelist dna contracts

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/index.tsx

We are not allowing this feature for now so disabling requesting it in the dev portal

Temporarily disable importing all contacts

---

web/lib/schema/index.ts

Allow punctuation but disallow \ and curly braces

fix: simplify regex and allow more punctuation

---

web/api/v2/minikit/send-notification/index.ts

Loosen the regex pattern for notifications

fix notifications regex

---

web/lib/schema/index.ts

fix: add ! to title regex

---

web/lib/categories.ts

fix: external localisation

---

hasura/metadata/databases/default/tables/public_membership.yaml
hasura/metadata/databases/default/tables/public_user.yaml

Reviewer needs these to display submission info

fix: grant perms to reviewer

---

web/legacy/backend/errors.ts
web/pages/api/v1/precheck/[app_id].ts

Enable skipping logs to reduce noisy logs

Enable skip logging

---

web/api/v2/public/apps/index.ts
web/package.json
web/pnpm-lock.yaml

Highlighted apps shouldn't be ranked by popularity but by the app_id order we specify

Preserve highlighted apps order

---

web/lib/schema/index.ts

allows `+` for telegram group links

fix: https link regex

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

This PR adds error handling and returns 404 status code when `draft_id` doesn't match the app's metdata.

Return 404 when `draft_id` is invalid

---

web/api/helpers/app-store.ts
web/tests/api/v2/minikit-app-metadata.test.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

You cannot even modify these values anymore in the dev portal

Remove unused descriptions

---

web/lib/languages.ts
web/tests/api/v2/public/apps/apps.test.ts

add thai and indo

---

web/lib/categories.ts

add missing translations for new locales

fix: translate category names

---

web/api/v2/public/apps/index.ts

Temp log countries

---

web/api/v2/public/apps/index.ts

Change log type

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

The post update check didn't include awaiting_review which resulted in us not being able to update it in coreapp

fix: update post-update check on app metadata

---

web/lib/constants.ts
web/lib/utils.ts
web/package.json
web/pnpm-lock.yaml

Reverts worldcoin/developer-portal#1184
Something broke IDKit verifications but I"m not sure what doesn't seem to be precheck so reverting this one

Revert "feat: Passport credential support"

---

web/pages/api/v1/precheck/[app_id].ts

Reverts worldcoin/developer-portal#1190

Revert "revert"

---

CODEOWNERS

messed up codeowners file

---

web/api/helpers/app-store.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/lib/utils.ts

we'll have icons for categories so we need to provide them in the /apps response 
decided to hardcode because they're static and directly coupled with the category id

provide icon urls for categories

---

web/lib/constants.ts
web/lib/utils.ts
web/package.json
web/pnpm-lock.yaml

Fixed here: https://github.com/worldcoin/idkit-js/pull/306

Bring this back and bump idkit

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Components/Kiosk/VerificationLevelPicker/index.tsx

Allow selecting document and secure document

Add new levels

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/tests/api/v2/public/apps/apps.test.ts

Reverts worldcoin/developer-portal#1196. Blocking pipeline since @michalstruck wanted to test please just PR again when ready. Need to merge razer stuff to unblock mobile

Revert "Remove external category"

---

web/lib/constants.ts

Add test partner to known partner team IDs

Add test partner to known partner team IDs

---

web/scenes/Portal/Profile/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

add a warn for sea countries, change copy on profile

add warns and change copy in profile

---

web/lib/utils.ts

Always return true for staging apps

Return true for staging apps

---

hasura/.dockerignore
web/.dockerignore

- Ensure .git and .gitignore are properly ignored
- Prevent sensitive files from being included in Docker builds

SEC-1406: dockerignore patch

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/tests/api/v2/public/apps/apps.test.ts

Revert "Revert "Remove external category""

---

web/api/hasura/create-app-report/index.ts

fix internal endpoint

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/tests/api/v2/public/apps/apps.test.ts

Reverts worldcoin/developer-portal#1211

Revert "Revert "Revert "Remove external category"""

---

web/api/v2/public/apps/index.ts
web/lib/categories.ts
web/tests/api/v2/public/apps/apps.test.ts

add a new property in the app store response that provides data for the special "all" category

provide icons for all category

---

web/api/v2/public/apps/index.ts
web/lib/categories.ts

add translations

---

web/api/v2/minikit/send-notification/index.ts
web/lib/schema/index.ts

Allow emojis for send notification

Allow emojis

---

web/api/v2/public/app/[app_id]/index.ts

allow company website to get single external apps 

---

web/lib/crypto.server.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/page/CreateActionModal/index.tsx

A user reported not being able to save an RSA PEM; this fix accounts for both types of PEMs to be saved.

update pem formatting issues

---

web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/pages/api/v1/precheck/[app_id].ts

This makes it easier for 'connect with World ID' to see who they are connecting with.

Add app website url to precheck

---

web/api/hasura/change-app-report-status/index.ts

when updating the action i forgot to change the acition.name in code. also updated errors

set action name to correct one

---

web/api/hasura/change-app-report-status/index.ts

adjust schema

---

web/lib/utils.ts

we didn't provide worldscan urls

Fix transaction urls

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Update the error response from send transaction.

Update the error message

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx

navigating to other pages and then back resulted in stale state, this fixes it

responsiveness

---

web/api/helpers/verify.ts
web/tests/api/helpers/verify.test.ts

Allow proofs to be submitted unpacked or packed.

Handle cases where a proof is a JSON value of a decoded proof

---

web/app/(portal)/teams/[teamId]/apps/[appId]/notifications/layout.tsx
web/app/(portal)/teams/[teamId]/apps/[appId]/notifications/page.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Notifications/layout.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Notifications/page.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/layout/index.tsx

errors/successes are toasts
Add a simple UI to allow manually sending notifications

feat: send notification UI

---

web/lib/categories.ts

merge after merging the deploy PR so that we're pointing to an actual image

add shopping cat

---

web/lib/categories.ts

make the category second to last

shopping second to last

---

web/api/helpers/app-store.ts
web/lib/types.ts

sort based on new users

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

supported_country checks

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

context: allow to edit countries in coreapp

allow reviewer to edit supported_countries

---

web/lib/constants.ts

Whitelisting DNA's new wallet app that will separate it from the original DNA app

whitelist dna wallet

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

fix: Remove dummy logs

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/api/v2/minikit/transaction/debug/index.ts
web/lib/schema/index.ts

Introduces a proxy to the transaction debug URL endpoint in [app-backend-main](https://github.com/worldcoin/app-backend-main/blob/ce06ea47f0ceda5c84bf7cd0fbd6a51963d1f5fc/src/transactions/transactions.internal.controller.ts#L76).

feat: Create transaction debug URL proxy

---

hasura/metadata/cron_triggers.yaml
web/api/delete-expired-notification-logs/graphql/get-expired-notification-log-ids-batch.generated.ts
web/api/delete-expired-notification-logs/graphql/get-expired-notification-log-ids-batch.graphql

limit cronjob

---

hasura/migrations/default/1743603595554_create_index_notification_log_wallet_address_notification_log_id_fkey_index/down.sql
hasura/migrations/default/1743603595554_create_index_notification_log_wallet_address_notification_log_id_fkey_index/up.sql

add an index on fkey not to do a seq scan on every cascade delete

add an index

---

hasura/migrations/default/1743603595554_create_index_notification_log_wallet_address_notification_log_id_fkey_index/up.sql

created the index manually but the migration didn't have the if exists clause

add if exists clause

---

web/lib/constants.ts

whitelist cash

---

web/api/v2/public/apps/index.ts

fix external filtering

---

web/api/v2/public/apps/index.ts
web/tests/api/v2/public/apps/apps.test.ts

actually filter out when either category or app mode are external

Fix filter logic

---

hasura/metadata/cron_triggers.yaml
web/api/delete-expired-notification-logs/graphql/get-expired-notification-log-ids-batch.graphql

the current rate is not overloading the db in any way, so we can bump to clear the tables faster

bump frequency and no of deleted records

---

web/api/delete-expired-notification-logs/graphql/get-expired-notification-log-ids-batch.generated.ts

the types and schema wasn't regenerated. good to merge on approve

regenerate gql

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/api/v2/public/constants.ts
web/tests/api/v2/public/apps/app.test.ts

add an appropriate response based on client version in the app single get endpoint too

add version filtering to single get too

---

web/tests/api/v2/minikit-transaction-debug.test.ts

Adds tests for the transaction debug URL endpoint.

feat: Add transaction debug URL endpoint tests

---

web/lib/constants.ts

Whitelist the DNA NFT app. Just merge

whitelist DNA NFT

---

web/pages/api/v1/oidc/introspect.ts
web/pages/api/v1/oidc/token.ts

OIDC is not accepting the header type with next-auth 5. Trying to see what's the issue

log header type

---

web/pages/api/v1/oidc/token.ts
web/tests/integration/oidc/token.test.ts

form-encoded sometimes have `application/x-www-form-urlencoded;charset=UTF-8`

Headers fixes

---

hasura/metadata/cron_triggers.yaml
hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1744599165683_alter_table_public_app_metadata_add_column_is_for_humans_only/down.sql
hasura/migrations/default/1744599165683_alter_table_public_app_metadata_add_column_is_for_humans_only/up.sql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.graphql
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.graphql
web/graphql/graphql.schema.json
web/graphql/graphql.ts

add a is for human only property, expose in endpoints

App store redesign

---

web/pages/api/v1/oidc/token.ts

Log token endpoint to understand why next auth5 doesn't work with OIDc

Log token endpoint

---

web/lib/schema/index.ts

11 chars now!

---

web/api/v2/public/app/[app_id]/index.ts

we should get it from CF so that when it's called from the client directly we can still filter

get country from cf when available

---

web/api/v2/public/app/[app_id]/index.ts

add flag to specify skipping the check from backend, for example for notifications or transaction history

skip country check flag

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

in form too

---

web/api/v2/public/app/[app_id]/index.ts

revert temp

---

web/api/v2/public/app/[app_id]/index.ts

Reverts worldcoin/developer-portal#1303

Revert "revert temp"

---

web/api/v2/public/apps/index.ts

Fixes the platform check, that should be filtering out the android apps instead of filtering them in for iOS.

fix: Fix platform check

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

we'll want to see and edit this in reviewer

grant select,update perms to reviewer on humans only, regen metadata

---

hasura/migrations/default/1744851798489_deduplicate_localisations/down.sql
hasura/migrations/default/1744851798489_deduplicate_localisations/up.sql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/graphql/server/fetch-localisation.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/graphql/server/fetch-localisation.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/server/submit.ts

Adds a check that no localisations exist for the same locale when creating a new localisation.

fix: Prevent localisation duplication during creation

---

web/api/v2/public/app/[app_id]/index.ts

temporarily disable country check

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/SetupForm/index.tsx

fix visual bug where you can set notifications on an already verified app

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

ui allows to set this when the metadata is already verified, or user has no perms. has no effect on actual data, ui bug

fix UI issue

---

web/api/v2/public/app/[app_id]/index.ts

Reverts worldcoin/developer-portal#1314

Revert "rename flag"

---

web/api/v2/public/app/[app_id]/index.ts

revert it after app-backend is merged

Revert "Revert "rename flag""

---

CODEOWNERS
web/api/v2/minikit/transaction/[transaction_id]/index.ts

The error message is a json but we were parsing as text and thus not propagating into minikit

fix error messages

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Transactions/page/server/getAccumulativeTransactionData.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/use-get-accumulative-transactions.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/index.tsx

This is simply a partial implementation of the transaction graph. Also app_id was hard coded

Add transaction graph logic

---

hasura/migrations/default/1744916435386_is_android_only_default_false/down.sql
hasura/migrations/default/1744916435386_is_android_only_default_false/up.sql

Remove unused migration @michalstruck make sure you fix this!

remove unused migration

---

web/api/v2/public/apps/index.ts
web/api/v2/public/constants.ts

temporarily enable grants for office ip

enable grants for office ip

---

web/api/v2/public/apps/index.ts
web/api/v2/public/constants.ts

Temp grants enable

---

web/api/v2/public/apps/index.ts

hacky solution to show grants from app backend, for testing

force show grants on param

---

web/lib/schema/index.ts

allow https links with mulitple hyphens

---

web/api/v2/public/apps/index.ts
web/api/v2/public/constants.ts

add more office ips, add env var

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx

adjust compliance copy
also updated the gambling copy to include poland and us

adjust text

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Notifications/page.tsx

Added posthog event to track when notification is successfully sent

---

web/api/helpers/app-store.ts
web/lib/constants.ts

move default pins (without not grants) to the bottom of the app store list

move invites,network,learn,contacts to bottom

---

web/api/hasura/create-new-draft/graphql/fetch-metadata.generated.ts
web/api/hasura/create-new-draft/graphql/fetch-metadata.graphql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/apps/graphql/get-app-rankings.generated.ts
web/api/v2/public/apps/graphql/get-highlighted-apps.generated.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/server/submit.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/graphql/client/fetch-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/graphql/client/fetch-app-metadata.graphql

made this property as well as is_android_only copy over when creating new drafts

add UI for is for humans only

---

web/api/hasura/create-new-draft/graphql/create-draft.generated.ts
web/api/hasura/create-new-draft/graphql/create-draft.graphql

fix drafts

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

change status to a unique one
needed for DEV-1645

change res status

---

web/lib/constants.ts

Add hold station

---

web/api/v2/minikit/transaction/debug/index.ts
web/tests/api/v2/minikit-transaction-debug.test.ts

Debug URL endpoint wasn't de-structuring the response properly

Try to fix debug url endpoitn

---

web/api/v2/verify/index.ts
web/tests/api/v2/verify.test.ts

The proof endpoint currently blocks you from verifying an action if your engine is not cloud. This is an unneeded restriction

Update proof endpoint

---

web/api/v2/minikit/transaction/debug/index.ts

This works now no need for the log

Remove old log

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml

add missing perms

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/AppStoreLocalised/ImageForm/index.tsx

meta tag user perms

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/TryAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/page/graphql/client/get-single-action.graphql

Hide the code snippet for mini apps since it was inccorect

hide code snippet for mini apps

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx

Show max verifications for on chain apps

Show max verifications for on chain apps

---

hasura/metadata/actions.graphql
web/graphql/graphql.schema.json
web/graphql/graphql.ts

add the images to show review images type

add the tag to gql types too

---

web/api/helpers/errors.ts
web/api/helpers/validate-request-schema.ts
web/api/v2/minikit/send-notification/index.ts

Include app_id in the error. So we can see who is triggering all these errors in the notificaiton service. We will understand what's causing these [log spikes](https://app.datadoghq.com/logs?query=%40env%3Aproduction%20service%3Adeveloper-portal%20status%3Awarn&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1745708400000&to_ts=1745710200000&live=false)

include app_id in the error

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/lib/utils.ts

Adds a retry function to the metrics call.

fix: Add fetch retry logic

---

web/api/v2/public/apps/index.ts

- Remove the temporary office IP whitelist
- Create a new param to let us see all apps regardless of country, will make it easier to pull all apps
- Cleaned up the code a bit and comments

Update apps endpoint

---

web/api/helpers/app-store.ts

Grants causes the algorithm to break

Remove grants from max

---

web/api/helpers/verify.ts
web/api/v1/oidc/authorize/index.ts
web/tests/api/helpers/verify.test.ts

Fixes handling of the signal hash in the proof verification.

fix: Fix signal hash handling

---

web/api/helpers/verify.ts
web/api/v1/oidc/authorize/index.ts
web/tests/api/helpers/verify.test.ts

This broke usernames and signals in proofs

Revert "fix: Fix signal hash handling"

---

web/api/v1/oidc/authorize/index.ts

There are hashing issues temporarily fixing it and adding a log. Basically sign in with world id doesn't use a hashed signal but it's unclear how that hashing should actually be done since dev portal only accepts hashed signal now. In the future we should update the sign in provider to also support hashed signal.

Temporary Signal Fix for hash 

---

web/api/v1/oidc/authorize/index.ts

Remove unused log

---

web/api/v1/oidc/authorize/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Actions/ActionId/Settings/UpdateAction/server/form-schema.ts

Bug fixes for update action rendering unneeded parentheses and also incorrect form validation

Remove unused log and fix update action

---

web/api/v2/public/constants.ts

remove leftover ip whitelist

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
hasura/migrations/default/1747148370416_alter_table_public_app_metadata_add_column_should_uninstall_on_delist/down.sql
hasura/migrations/default/1747148370416_alter_table_public_app_metadata_add_column_should_uninstall_on_delist/up.sql
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.generated.ts
web/api/v2/public/app/[app_id]/graphql/get-app-metadata.graphql
web/api/v2/public/app/[app_id]/index.ts
web/graphql/graphql.schema.json
web/graphql/graphql.ts
web/tests/api/v2/public/apps/app.test.ts

as per legal requirements, apps will be deeplinkable despite country restrictions
this also causes apps to be hidden from home screen when the new flag is set
ref DEV-1729

change deeplinking and delisting logic

---

web/api/helpers/app-store.ts
web/api/v2/public/apps/index.ts

The return value is getting way too large as a payload
This cuts it down by removing the often lengthy country list, and replacing it with a single country (the one user is in)

set the country list to current country only to compress res

---

web/api/hasura/ban-app/index.ts
web/api/hasura/create-app-report/index.ts
web/api/hasura/create-new-draft/index.ts
web/api/hasura/get-app-review-images/index.ts
web/api/hasura/get-image/index.ts
web/api/hasura/get-unverified-images/index.ts
web/api/hasura/invite-team-members/index.ts
web/api/hasura/reset-api-key/index.ts
web/api/hasura/reset-client-secret/index.ts
web/api/hasura/unban-app/index.ts
web/api/hasura/upload-image/index.ts
web/api/hasura/validate-localisation/index.ts
web/api/hasura/verify-app/index.ts
web/api/helpers/errors.ts
web/api/join-callback/index.ts
web/api/login-callback/index.ts
web/api/v1/oidc/authorize/index.ts
web/api/v1/oidc/introspect/index.ts
web/api/v1/oidc/token/index.ts
web/api/v2/app/submit-app-review/index.ts
web/api/v2/create-action/index.ts
web/api/v2/minikit/app-metadata/[app_id]/index.ts
web/api/v2/minikit/send-notification/index.ts
web/api/v2/minikit/transaction/[transaction_id]/index.ts
web/api/v2/minikit/transaction/debug/index.ts
web/api/v2/verify/index.ts
web/tests/api/v2/verify.test.ts
web/tests/integration/oidc/authorize.test.ts

Adds the `app_id` and `team_id` to all logs in the endpoints.
Remaining pages router endpoints will be updated after the migration.

feat: Add App Id and Team Id to all logs

---

web/lib/constants.ts

add survey bull

---

web/api/v2/minikit/send-notification/index.ts
web/lib/schema/index.ts

allow special string to sub in usernames in notiifcations

allow special username placeholder

---

web/api/v2/public/apps/index.ts

remove stale validation rule

---

web/lib/languages.ts

Support Trad Chinese

---

web/lib/languages.ts

Update Taiwan Chinese label

---

web/lib/languages.ts

Improve Chinese locale parsing

---

web/api/v2/verify/index.ts
web/tests/api/v2/verify.test.ts

Update nullifier feat flag

---

web/api/v2/verify/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/QrQuickAction/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/index.tsx

Hide QR quick action if `integration_url` is empty

---

web/api/helpers/app-store.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/AppStatsGraph/GraphsSection/index.tsx

add tooltip for notif badge eligibility

add tooltip on badge eligibility

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts
web/api/v2/public/constants.ts
web/lib/compare-versions.ts
web/lib/compare-versions.unit.spec.ts
web/lib/constants.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

Reverts worldcoin/developer-portal#1432

Revert "remove versioning completely"

---

web/api/_evaluate-app-notification-permissions/index.ts

This won't spam since it runs once a week and we'll get insights into what's happening

add logs for notif evaluations

---

web/api/v2/minikit/send-notification/index.ts

This log is not helpful. But it's being triggered a ton. 
https://app.datadoghq.com/logs?query=service%3Adeveloper-portal&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZc8GZcl7Dbi3gAAABhBWmM4R1pkTEFBQVB1b0VfdjhaSnJBQUEAAAAkMDE5NzNjMTktOThmZi00MDRmLTg1MTItNWZmYmZjMWFhMjJiAAA5hQ&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1749059400000&to_ts=1749060000000&live=false

cleanup logs

---

web/lib/categories.ts

Add Trad Chinese localised categories

---

hasura/metadata/cron_triggers.yaml
web/api/_evaluate-app-notification-permissions/graphql/get-notification-evaluation-apps.generated.ts
web/api/_evaluate-app-notification-permissions/graphql/get-notification-evaluation-apps.graphql
web/api/_evaluate-app-notification-permissions/index.ts

Add auth header

---

web/api/join-callback/index.ts

Replaces 403 response with a redirect to 401 page.

feat: Redirect to 401 page in invite email doesn't match

---

web/api/v2/public/app/[app_id]/index.ts
web/api/v2/public/apps/index.ts

add headers so CF can compress

add content-length headers

---

hasura/metadata/databases/default/tables/public_app_metadata.yaml
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/NotificationPauseSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-is-app-notifications-disabled.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/graphql/client/get-is-app-notifications-disabled.graphql

the alert was not showing because user lacked permissions

fix perms and regen

---

web/api/v2/minikit/user-grant-cycle/index.ts
web/tests/api/v2/minikit-user-grant-cycle.test.ts

Fix user grant cycle response parsing

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Notifications/page.tsx

update docs link after restructure

update docs link

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Danger/page/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/layout/constants-temp.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/layout/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/page.tsx

This reverts commit ec004bff55b52b0829cd83a08ea55305cdfc1ab7.

Revert "FF refactor for internal teams (#1490)"

---

web/api/helpers/app-store.ts
web/tests/api/v2/public/apps/app.test.ts
web/tests/api/v2/public/apps/apps.test.ts

Button copy says use integration we should change that to Get Mini App

Fix: button copy

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/server/submit.ts

Improve schema validation

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Advanced/page/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStore/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBar/SubmitAppModal/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBar/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/BasicInformation/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/Danger/page/DeleteModal/index.tsx

add noUnknown

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/QuickActionsSection/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/page/index.tsx

Fix create action button issue. Bug from a while ago but was using some hard coded constant

Fix: create action button

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/page/server/index.ts

We are updating metrics service to serve stats by country. UI is broken now so we are fixing

fix dev portal ui

---

web/api/helpers/app-store.ts

fix comments

---

web/api/hasura/invalidate-cache/index.ts

Introducing a 1 minute lock on invalidate cache after it is fired.

Prevent invalidate cache from being fired multiple times in succession

---

hasura/Dockerfile

Adds fixed platform to Hasura Dockerfile, allowing for local CDK deploys.

feat: Add platform to Dockerfile

---

web/api/helpers/fetch-metrics.ts

fix metrics

---

tests/api/.env.development
tests/api/global.d.ts
tests/api/helpers/auth-helper.ts
tests/api/jest.config.ts
tests/api/pnpm-lock.yaml
tests/api/specs/auxiliary/auxiliary-endpoints.spec.ts
tests/api/specs/public/public-apps.spec.ts

- Add tests for all auxiliary endpoints: _delete-jwks, _evaluate-app-notification-permissions, _gen-external-nullifier, _increment-app-stats, delete-expired-notification-logs

Add tests for Auxiliary endpoints

---

web/lib/utils.ts

The previous implementation used `AbortSignal.timeout(fetchTimeoutInMS)`, as recommended by MDN documentation. However, this approach has an edge case: the timeout signal is not cleared after a successful fetch call. As a result, there’s a potential race condition where the fetch completes successfully, but the timeout triggers before the response body is fully read—causing an unexpected error.
To address this, a new helper function utilizing `AbortController` has been introduced. It ensures that the timeout signal is explicitly cleared immediately after the fetch completes, preventing erroneous timeouts during response processing.

fix: Fix edge case of fetch signal timeout

---

web/lib/languages.ts

Fix case sensitivity, this is case sensitive needs to be fixed

fix case sensitivity on country check

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/LogoImageUpload/index.tsx

add an additional condition to skeleton that fixes an edge case

fix loading state&remove stale comment

---

web/api/hasura/create-new-draft/index.ts

Ticket - [DEV-2162](https://linear.app/worldcoin/issue/DEV-2162/dev-portal-investigate-500-in-post-apihasuracreate-new-draft)
Verifies that there's an existing verified app metadata before creating a new draft.

fix: Add a check for verified app metadata existence

---

web/api/v2/public/app/[app_id]/index.ts
web/tests/api/v2/public/apps/app.test.ts

Fix issue where other languages doesn't work as they are non ASCII characters. Thus we need to be explicit about utf-8

needs to be utf8

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/LogoImageUpload/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/app-store-refactored.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/components/FormSections/LogoSection.tsx

update logo edit ui

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/FormSchema/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/FormSchema/types.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/utils/dataTransforms.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/graphql/server/fetch-review-app-metadata.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/graphql/server/fetch-review-app-metadata.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppTopBarRefactored/server/submit.ts

additional checks

---

web/Dockerfile
web/instrumentation.ts
web/next.config.mjs

Reverts worldcoin/developer-portal#1566

Revert "feat: Add dd-trace setup"

---

web/lib/schema/index.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/FormSchema/form-schema.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/components/FormSections/LocalisationsSection/components/LocalisationFields.tsx

Two validators had missing messages, which resulted in "raw" messages being shown to user. This adds a pretty msg

add missing messages

---

web/scenes/Portal/Teams/TeamId/Apps/AppId/Configuration/AppStoreRefactored/components/FormSections/CountriesSection.tsx

adjust copy, requested by legal

adjust copy and links

---

web/api/hasura/invite-team-members/index.ts

Ticket - [DEV-2204](https://linear.app/worldcoin/issue/DEV-2204/h1-developer-portal-allows-bypassing-the-restriction-on-inviting)
Trims and lowercases all invite emails to avoid duplicates.

feat: Add invite email normalization

---

tests/api/package.json

Skip tests

---

tests/api/.env.development
tests/api/package.json
tests/api/specs/hasura/get-image.spec.ts
tests/api/specs/public/public-apps.spec.ts

Fix e2e tests

---

web/api/hasura/verify-app/graphql/getAppMetadata.generated.ts
web/api/hasura/verify-app/graphql/getAppMetadata.graphql
web/api/hasura/verify-app/index.ts

fix: Copy content card image on app verification

---

hasura/metadata/databases/default/tables/public_action.yaml
hasura/metadata/databases/default/tables/public_redirect.yaml
hasura/migrations/default/1758807520730_remove_sign_in_with_world_id/down.sql
hasura/migrations/default/1758807520730_remove_sign_in_with_world_id/up.sql
hasura/seeds/default/1678146469554_actionSeed.sql
hasura/seeds/default/1678146566240_redirectSeed.sql
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/graphql/client/fetch-sign-in-action.generated.ts
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/graphql/client/fetch-sign-in-action.graphql
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/ClientInformation/index.tsx
web/scenes/Portal/Teams/TeamId/Apps/AppId/SignInWithWorldId/page/index.tsx
web/tests/integration/action.test.ts

Ticket - [DEV-2298](https://linear.app/worldcoin/issue/DEV-2298/dev-portal-add-deprecation-notice-for-sign-in-with-world-id)
* Adds a warning message for all users, informing about the deprecation of `Sign in with World ID`
* Blocks this feature for all apps created after September 29, 2025
* Removes permissions to add redirects or Sign in with World ID actions for all apps created after September 29, 2025 
* Removes the trigger, creating Sign in with World ID actions on app creation

feat: Deprecate Sign in with World ID

---

web/api/hasura/verify-app/index.ts
web/api/helpers/image-processing.ts
web/api/v2/public/app/[app_id]/index.ts

Ticket - [DEV-2311](https://linear.app/worldcoin/issue/DEV-2311/dev-portal-add-a-field-for-rounded-logo-images)
Create rounded logo image on app verification and adds this field to the public endpoint.

feat: Create rounded logo images

---

web/api/v2/public/app/[app_id]/index.ts

feat: Fix rounded image extension

---

web/api/v2/minikit/transaction/[transaction_id]/index.ts

Ticket - [DEV-2322](https://linear.app/worldcoin/issue/DEV-2322/dev-portal-investigate-get-transaction-endpoint-failures) & [DEV-2309](https://linear.app/worldcoin/issue/DEV-2309/fix-transaction-endpoint-error-propagation)
* Increases the request timeout to 5 seconds (we have some requests that take more than 3 seconds on the app backend side)
* Fixes the error propagation from app backend

feat: Increase request timeout
